// AUTO-GENERATED by scripts/lex-codegen.ts. DO NOT EDIT BY HAND.
//
// Run `aube run lex:codegen` after editing any
// lexicons/dev/cocore/compute/*.json. CI verifies the on-disk file
// matches a fresh regeneration; a stale types.gen.ts fails the
// build.
//
// The hand-maintained twin packages/sdk/src/types.ts is the
// canonical export today. types.gen.ts is the drift-detection
// canary — a follow-up PR swaps types.ts to re-export from this
// file once the shapes match end-to-end across all consumers.

export interface Money {
  amount: number;
  currency: string;
}

export interface StrongRef {
  uri: string;
  cid: string;
}

export interface ModelPrice {
  modelId: string;
  inputPricePerMTok: number;
  outputPricePerMTok: number;
  currency: string;
}

export interface TokenRate {
  inputPricePerMTok: number;
  outputPricePerMTok: number;
  currency: string;
}

export type TrustLevel = "self-attested" | "hardware-attested";

export type Tier = "attested-confidential" | "best-effort";

export type SettlementStatus = "settled" | "refunded" | "disputed";

export interface FriendRecord {
  subject: string;
  subjectHandle?: string;
  note?: string;
  createdAt: string;
}

export interface ProfileRecord {
  displayName?: string;
  bio?: string;
  avatar?: { ref: string; mimeType: string; size: number };
  avatarUrl?: string;
  handle?: string;
  createdAt: string;
  updatedAt?: string;
}

export interface TokenGrantRecord {
  exchange: string;
  recipient: string;
  amount: number;
  policy: StrongRef;
  createdAt: string;
}

export interface TokenPatronageRecord {
  exchange: string;
  recipient: string;
  period: Record<string, unknown>;
  patronageScore: number;
  totalPatronage: number;
  tokensCredited: number;
  treasuryBefore: number;
  policy: StrongRef;
  createdAt: string;
}

export interface AttestationRecord {
  publicKey: string;
  encryptionPubKey: string;
  sigScheme?: "p256" | "appattest-assertion";
  encScheme?: "x25519" | "p256-ecies-se";
  chipName: string;
  hardwareModel: string;
  serialNumberHash: string;
  osVersion: string;
  binaryHash: string;
  cdHash?: string;
  teamId?: string;
  hardenedRuntime?: boolean;
  libraryValidation?: boolean;
  getTaskAllow?: boolean;
  metallibHash?: string;
  engineLibHash?: string;
  inProcessBackend?: boolean;
  antiDebug?: boolean;
  coreDumpsDisabled?: boolean;
  envScrubbed?: boolean;
  sipEnabled: boolean;
  secureBootEnabled: boolean;
  secureEnclaveAvailable: boolean;
  authenticatedRootEnabled: boolean;
  rdmaDisabled?: boolean;
  mdaCertChain?: string[];
  appAttest?: { object: string; keyId: string };
  selfSignature: string;
  attestedAt: string;
  expiresAt: string;
  tier?: Tier;
}

export interface DisputeRecord {
  settlement: StrongRef;
  exchange: string;
  raisedBy: string;
  raisedAt: string;
  reason: Record<string, unknown>;
  status: "open" | "resolved";
  outcome?: Record<string, unknown>;
  evidenceCid?: string;
  sig?: string;
  createdAt: string;
}

export interface ExchangeAttestationRecord {
  exchange: string;
  policy: StrongRef;
  softwareVersion: string;
  signingKeyFingerprint: string;
  auditPosture?: string;
  createdAt: string;
}

export interface ExchangePolicyRecord {
  exchange: string;
  fee: Record<string, unknown>;
  tokenRate?: TokenRate;
  supportedCurrencies: string[];
  selfLoop: Record<string, unknown>;
  processor?: string;
  termsUri?: string;
  termsVersion?: string;
  tokenGrant?: number;
  tokenFloor?: number;
  treasuryDid?: string;
  weeklyRefresh?: Record<string, unknown>;
  patronageDistribution?: Record<string, unknown>;
  active?: boolean;
  createdAt: string;
}

export interface JobRecord {
  model: string;
  inputCommitment: string;
  inputFormat?: "text" | "messages-v1";
  inputCipherURL?: string;
  maxTokensOut: number;
  priceCeiling: Money;
  acceptedProviders?: string[];
  acceptedTrustLevel: TrustLevel;
  acceptedExchanges?: string[];
  paymentAuthorization: StrongRef;
  nonce: string;
  expiresAt: string;
  createdAt: string;
  outputSchema?: { name?: string; strict?: boolean; schema?: Record<string, unknown> };
  tools?: { type: "function"; function: { name: string; description?: string; parameters?: Record<string, unknown> } }[];
  toolChoice?: "auto" | "none" | "required";
  toolChoiceFunction?: string;
}

export interface PaymentAuthorizationRecord {
  exchange: string;
  ceiling: Money;
  scope: "singleJob" | "session";
  sessionBudget?: Money;
  nonce: string;
  expiresAt: string;
  createdAt: string;
}

export interface ProviderRecord {
  machineLabel: string;
  chip: string;
  ramGB: number;
  gpuCores?: number;
  memoryBandwidthGBs?: number;
  cpuCores?: number;
  pCores?: number;
  eCores?: number;
  modelIdentifier?: string;
  os?: string;
  supportedModels: string[];
  desiredModels?: string[];
  priceList: ModelPrice[];
  encryptionPubKey: string;
  attestationPubKey: string;
  trustLevel: TrustLevel;
  tier?: Tier;
  desiredTier?: Tier;
  acceptedExchanges?: string[];
  proBono?: Record<string, unknown>;
  contactEndpoint?: string;
  active?: boolean;
  provisioning?: boolean;
  serving?: boolean;
  payoutsEnabled?: boolean;
  binaryVersion?: string;
  engineFault?: { code: string; message: string; models?: string[]; at: string };
  attestationFault?: { code: string; message: string; at: string };
  advisorFault?: { code: string; message: string; observedAt: string };
  toolCalls?: boolean;
  shareLocation?: boolean;
  region?: string;
  regionSource?: string;
  regionObservedAt?: string;
  createdAt: string;
}

export interface ReceiptRecord {
  job: StrongRef;
  requester: string;
  model: string;
  inputCommitment: string;
  outputCommitment: string;
  outputCipherCommitment?: string;
  reasoningCommitment?: string;
  sessionKeyCommitment?: string;
  sessionNonce?: string;
  params?: Record<string, unknown>;
  outputCipherURL?: string;
  tokens: { in: number; out: number };
  startedAt: string;
  completedAt: string;
  price: Money;
  attestation: StrongRef;
  enclaveSignature: string;
  tier?: Tier;
  proBono?: boolean;
  brokerageCountersignature?: Record<string, unknown>;
}

export interface SettlementRecord {
  receipt: StrongRef;
  requesterAuthorization: StrongRef;
  amountCharged: Money;
  providerPayout: Money;
  exchangeFee: Money;
  processorReference: string;
  status: SettlementStatus;
  refundOf?: StrongRef;
  policy?: StrongRef;
  exchangeAttestation?: StrongRef;
  sig?: string;
  settledAt: string;
}

export interface TermsAcceptanceRecord {
  exchange: string;
  policy: StrongRef;
  termsVersion: string;
  termsUri: string;
  userAgent?: string;
  acceptedAt: string;
  attestation?: StrongRef;
  sig?: string;
}

/** Lexicon-NSID-keyed lookup for the body type of an indexed record. */
export type CocoreRecord =
  | ({ $collection: "dev.cocore.account.friend" } & FriendRecord)
  | ({ $collection: "dev.cocore.account.profile" } & ProfileRecord)
  | ({ $collection: "dev.cocore.account.tokenGrant" } & TokenGrantRecord)
  | ({ $collection: "dev.cocore.account.tokenPatronage" } & TokenPatronageRecord)
  | ({ $collection: "dev.cocore.compute.attestation" } & AttestationRecord)
  | ({ $collection: "dev.cocore.compute.dispute" } & DisputeRecord)
  | ({ $collection: "dev.cocore.compute.exchangeAttestation" } & ExchangeAttestationRecord)
  | ({ $collection: "dev.cocore.compute.exchangePolicy" } & ExchangePolicyRecord)
  | ({ $collection: "dev.cocore.compute.job" } & JobRecord)
  | ({ $collection: "dev.cocore.compute.paymentAuthorization" } & PaymentAuthorizationRecord)
  | ({ $collection: "dev.cocore.compute.provider" } & ProviderRecord)
  | ({ $collection: "dev.cocore.compute.receipt" } & ReceiptRecord)
  | ({ $collection: "dev.cocore.compute.settlement" } & SettlementRecord)
  | ({ $collection: "dev.cocore.compute.termsAcceptance" } & TermsAcceptanceRecord);

export const COLLECTIONS = [
  "dev.cocore.account.friend",
  "dev.cocore.account.profile",
  "dev.cocore.account.tokenGrant",
  "dev.cocore.account.tokenPatronage",
  "dev.cocore.compute.attestation",
  "dev.cocore.compute.dispute",
  "dev.cocore.compute.exchangeAttestation",
  "dev.cocore.compute.exchangePolicy",
  "dev.cocore.compute.job",
  "dev.cocore.compute.paymentAuthorization",
  "dev.cocore.compute.provider",
  "dev.cocore.compute.receipt",
  "dev.cocore.compute.settlement",
  "dev.cocore.compute.termsAcceptance",
] as const;

export type CollectionId = (typeof COLLECTIONS)[number];

/** A row as seen by an AppView indexer or an exchange firehose
 *  subscriber. The wire shape is invariant across both consumers. */
export interface IndexedRecord<T = unknown> {
  uri: string;
  cid: string;
  collection: string;
  repo: string;
  rkey: string;
  body: T;
}
