#!/usr/bin/env node
// Custom TypeScript codegen for dev.cocore.compute.* lexicons.
//
// Reads every JSON file under `lexicons/dev/cocore/compute/` and
// emits a single `packages/sdk/src/types.gen.ts` containing the
// `*Record` interfaces, the discriminated `CocoreRecord` union,
// and the COLLECTIONS array. Mirrors the hand-maintained
// `packages/sdk/src/types.ts` shape verbatim where possible.
//
// We rolled our own rather than using `@atproto/lex-cli` because:
//   * lex-cli's output is volatile across versions (0.9 renamed
//     gen-api → build, with stricter cross-namespace ref handling).
//   * cocore's lexicon is small + uniformly shaped; the codegen
//     fits in a few hundred lines.
//   * lex-cli also produces a `lexicons` runtime registry that we
//     hand-write in `lex-runtime.ts` (so the registry has a
//     curated import order); standardizing on a tool we don't use
//     halfway is more friction than benefit.
//
// Usage:
//   aube run lex:codegen
//   make lex-codegen
//
// In CI, `lex-codegen-check` invokes this in dry-run mode and
// fails if the on-disk types.gen.ts no longer matches the
// regeneration. Anyone editing a lexicon must rerun codegen.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { argv } from "node:process";

interface PropertyDef {
  type: string;
  format?: string;
  ref?: string;
  items?: PropertyDef;
  knownValues?: string[];
  description?: string;
  properties?: Record<string, PropertyDef>;
  required?: string[];
}

interface LexiconDoc {
  lexicon: number;
  id: string;
  description?: string;
  defs: Record<
    string,
    {
      type: string;
      key?: string;
      record?: { type: "object"; required?: string[]; properties: Record<string, PropertyDef> };
      properties?: Record<string, PropertyDef>;
      required?: string[];
      description?: string;
      knownValues?: string[];
    }
  >;
}

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = dirname(SCRIPT_DIR);
// Top-level cocore namespace; we scan every JSON file under
// `lexicons/dev/cocore/<sub>/*.json`. Today that's `compute/` (the
// receipts of work) + `account/` (per-user cocore profile).
const LEX_ROOT = join(REPO_ROOT, "lexicons", "dev", "cocore");
const LEX_SUBDIRS = ["compute", "account"] as const;
const OUT_PATH = join(REPO_ROOT, "packages", "sdk", "src", "types.gen.ts");

const HAND_WRITTEN_PRELUDE = `// AUTO-GENERATED by scripts/lex-codegen.ts. DO NOT EDIT BY HAND.
//
// Run \`aube run lex:codegen\` after editing any
// lexicons/dev/cocore/compute/*.json. CI verifies the on-disk file
// matches a fresh regeneration; a stale types.gen.ts fails the
// build.
//
// The hand-maintained twin packages/sdk/src/types.ts is the
// canonical export today. types.gen.ts is the drift-detection
// canary — a follow-up PR swaps types.ts to re-export from this
// file once the shapes match end-to-end across all consumers.

export interface Money {
  amount: number;
  currency: string;
}

export interface StrongRef {
  uri: string;
  cid: string;
}

`;

const HAND_WRITTEN_TAIL = `

/** A row as seen by an AppView indexer or an exchange firehose
 *  subscriber. The wire shape is invariant across both consumers. */
export interface IndexedRecord<T = unknown> {
  uri: string;
  cid: string;
  collection: string;
  repo: string;
  rkey: string;
  body: T;
}
`;

/** Map from a lexicon NSID like dev.cocore.compute.receipt to the
 *  TypeScript interface name we emit (ReceiptRecord). The transform
 *  capitalizes the last segment and appends "Record". */
function nsidToInterface(nsid: string): string {
  const last = nsid.split(".").pop() ?? nsid;
  return last.charAt(0).toUpperCase() + last.slice(1) + "Record";
}

/** Convert a lexicon `ref` to a TS type. `com.atproto.repo.strongRef`
 *  becomes `StrongRef`; `dev.cocore.compute.defs#money` becomes
 *  `Money`; cross-NSID refs become the matching *Record interface. */
function refToType(ref: string): string {
  if (ref === "com.atproto.repo.strongRef") return "StrongRef";
  if (ref.endsWith("#money")) return "Money";
  if (ref.endsWith("#tokenCounts")) return "{ in: number; out: number }";
  if (ref.endsWith("#modelPrice")) return "ModelPrice";
  if (ref.endsWith("#tokenRate")) return "TokenRate";
  if (ref.endsWith("#trustLevel")) return "TrustLevel";
  if (ref.endsWith("#tier")) return "Tier";
  if (ref.endsWith("#settlementStatus")) return "SettlementStatus";
  // Inline-fallback: use a Record<string, unknown> for unknown refs
  // rather than crashing — keeps codegen forward-compatible.
  return "Record<string, unknown>";
}

function tsTypeFor(prop: PropertyDef): string {
  switch (prop.type) {
    case "string":
      if (prop.knownValues && prop.knownValues.length > 0) {
        // Closed-set string union. The lexicon `knownValues` is
        // documented as a hint — we treat it as exhaustive here for
        // type safety. If a record carries an unknown value at
        // runtime, the SDK's lexicon validator catches it.
        return prop.knownValues.map((v) => JSON.stringify(v)).join(" | ");
      }
      return "string";
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "bytes":
      return "string"; // bytes are base64 strings on the wire
    case "cid-link":
      return "string";
    case "array":
      if (prop.items) return `${tsTypeFor(prop.items)}[]`;
      return "unknown[]";
    case "object":
      if (prop.properties) return inlineObject(prop);
      return "Record<string, unknown>";
    case "ref":
      if (prop.ref) return refToType(prop.ref);
      return "unknown";
    case "blob":
      return "{ ref: string; mimeType: string; size: number }";
    case "unknown":
      return "unknown";
    default:
      return "unknown";
  }
}

function inlineObject(prop: PropertyDef): string {
  if (!prop.properties) return "Record<string, unknown>";
  const required = new Set(prop.required ?? []);
  const fields = Object.entries(prop.properties).map(([k, v]) => {
    const opt = required.has(k) ? "" : "?";
    return `${k}${opt}: ${tsTypeFor(v)}`;
  });
  return `{ ${fields.join("; ")} }`;
}

function emitInterface(name: string, def: { record?: NonNullable<LexiconDoc["defs"][string]["record"]> }): string {
  const rec = def.record;
  if (!rec) return "";
  const required = new Set(rec.required ?? []);
  const lines: string[] = [`export interface ${name} {`];
  for (const [k, v] of Object.entries(rec.properties)) {
    const opt = required.has(k) ? "" : "?";
    lines.push(`  ${k}${opt}: ${tsTypeFor(v)};`);
  }
  lines.push("}");
  return lines.join("\n");
}

/** Defs-only lexicons (no `record` def) emit shared types. We hand
 *  out a closed enum for `trustLevel` + `settlementStatus`, an
 *  interface for `modelPrice`. `money` and `tokenCounts` are
 *  handled inline via refToType. */
function emitDefsExports(doc: LexiconDoc): string {
  const lines: string[] = [];
  for (const [name, def] of Object.entries(doc.defs)) {
    if (def.type === "string" && def.knownValues) {
      const union = def.knownValues.map((v) => JSON.stringify(v)).join(" | ");
      lines.push(`export type ${cap(name)} = ${union};`);
    } else if (def.type === "object" && def.properties && name === "modelPrice") {
      const required = new Set(def.required ?? []);
      const fields: string[] = [];
      for (const [k, v] of Object.entries(def.properties)) {
        const opt = required.has(k) ? "" : "?";
        fields.push(`  ${k}${opt}: ${tsTypeFor(v)};`);
      }
      lines.push(`export interface ModelPrice {\n${fields.join("\n")}\n}`);
    } else if (def.type === "object" && def.properties && name === "tokenRate") {
      const required = new Set(def.required ?? []);
      const fields: string[] = [];
      for (const [k, v] of Object.entries(def.properties)) {
        const opt = required.has(k) ? "" : "?";
        fields.push(`  ${k}${opt}: ${tsTypeFor(v)};`);
      }
      lines.push(`export interface TokenRate {\n${fields.join("\n")}\n}`);
    }
    // money + tokenCounts are inlined via refToType, skip
  }
  return lines.join("\n\n");
}

function cap(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function readLexicons(): LexiconDoc[] {
  const docs: LexiconDoc[] = [];
  for (const sub of LEX_SUBDIRS) {
    const dir = join(LEX_ROOT, sub);
    for (const f of readdirSync(dir)) {
      if (!f.endsWith(".json")) continue;
      docs.push(JSON.parse(readFileSync(join(dir, f), "utf-8")) as LexiconDoc);
    }
  }
  docs.sort((a, b) => a.id.localeCompare(b.id));
  return docs;
}

function generate(): string {
  const docs = readLexicons();
  const blocks: string[] = [HAND_WRITTEN_PRELUDE.trimEnd()];

  // Defs file goes first (TrustLevel, SettlementStatus, ModelPrice).
  const defsDoc = docs.find((d) => d.id === "dev.cocore.compute.defs");
  if (defsDoc) blocks.push(emitDefsExports(defsDoc));

  // Per-record interfaces.
  for (const doc of docs) {
    if (doc.id === "dev.cocore.compute.defs") continue;
    const ifaceName = nsidToInterface(doc.id);
    const main = doc.defs["main"];
    if (!main || !main.record) continue;
    blocks.push(emitInterface(ifaceName, main as { record: NonNullable<LexiconDoc["defs"][string]["record"]> }));
  }

  // CocoreRecord discriminated union + COLLECTIONS list. The list
  // is a stable, ordered tuple that matches the hand-maintained
  // types.ts ordering for byte-stable output.
  const recordDocs = docs.filter((d) => d.id !== "dev.cocore.compute.defs" && d.defs["main"]?.record);
  const unionMembers = recordDocs
    .map(
      (d) =>
        `({ $collection: ${JSON.stringify(d.id)} } & ${nsidToInterface(d.id)})`,
    )
    .join("\n  | ");
  blocks.push(
    `/** Lexicon-NSID-keyed lookup for the body type of an indexed record. */\nexport type CocoreRecord =\n  | ${unionMembers};`,
  );
  const collections = recordDocs.map((d) => JSON.stringify(d.id)).join(",\n  ");
  blocks.push(
    `export const COLLECTIONS = [\n  ${collections},\n] as const;\n\nexport type CollectionId = (typeof COLLECTIONS)[number];`,
  );

  blocks.push(HAND_WRITTEN_TAIL.trimStart());
  // oxfmt-compliant: exactly one trailing newline. The HAND_WRITTEN_TAIL
  // template literal already ends with `\n`; trimEnd + add one keeps
  // the output stable regardless of accidental whitespace creep.
  return blocks.join("\n\n").trimEnd() + "\n";
}

function main(): void {
  const out = generate();
  const wantCheck = argv.includes("--check");
  if (wantCheck) {
    const onDisk = readFileSync(OUT_PATH, "utf-8");
    if (onDisk !== out) {
      console.error(
        "[lex-codegen] types.gen.ts is out of sync with the lexicons.\n" +
          "Run `aube run lex:codegen` and commit the result.",
      );
      process.exit(1);
    }
    console.error("[lex-codegen] types.gen.ts is up to date");
    return;
  }
  writeFileSync(OUT_PATH, out);
  console.error(`[lex-codegen] wrote ${OUT_PATH} (${out.length} bytes)`);
}

main();
