/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgDotpngRouteImport } from './routes/og[.]png'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as HeaderLayoutRouteImport } from './routes/_header-layout'
import { Route as DocsHeaderLayoutRouteImport } from './routes/_docs-header-layout'
import { Route as LexiconsIndexRouteImport } from './routes/lexicons.index'
import { Route as HeaderLayoutIndexRouteImport } from './routes/_header-layout.index'
import { Route as XrpcDevDotcocoreDotaccountDotrevokeApiKeyRouteImport } from './routes/xrpc.dev[.]cocore[.]account[.]revokeApiKey'
import { Route as XrpcDevDotcocoreDotaccountDotlistApiKeysRouteImport } from './routes/xrpc.dev[.]cocore[.]account[.]listApiKeys'
import { Route as XrpcDevDotcocoreDotaccountDotdeleteApiKeyRouteImport } from './routes/xrpc.dev[.]cocore[.]account[.]deleteApiKey'
import { Route as XrpcDevDotcocoreDotaccountDotcreateApiKeyRouteImport } from './routes/xrpc.dev[.]cocore[.]account[.]createApiKey'
import { Route as V1RecommendedModelsRouteImport } from './routes/v1.recommended-models'
import { Route as V1ModelsRouteImport } from './routes/v1.models'
import { Route as LexiconsNsidRouteImport } from './routes/lexicons.$nsid'
import { Route as ExchangeDidDotjsonRouteImport } from './routes/exchange.did[.]json'
import { Route as AgentVersionRouteImport } from './routes/agent.version'
import { Route as AgentUninstallRouteImport } from './routes/agent.uninstall'
import { Route as AgentPolicyRouteImport } from './routes/agent.policy'
import { Route as AgentInferenceRouteImport } from './routes/agent.inference'
import { Route as AgentDlRouteImport } from './routes/agent.dl'
import { Route as AgentBinaryHashesRouteImport } from './routes/agent.binary-hashes'
import { Route as AgentAppRouteImport } from './routes/agent.app'
import { Route as HeaderLayoutTermsRouteImport } from './routes/_header-layout.terms'
import { Route as HeaderLayoutStartRouteImport } from './routes/_header-layout.start'
import { Route as HeaderLayoutPrivacyRouteImport } from './routes/_header-layout.privacy'
import { Route as HeaderLayoutModelsRouteImport } from './routes/_header-layout.models'
import { Route as HeaderLayoutLeaderboardRouteImport } from './routes/_header-layout.leaderboard'
import { Route as HeaderLayoutJobsRouteImport } from './routes/_header-layout.jobs'
import { Route as HeaderLayoutFriendsRouteImport } from './routes/_header-layout.friends'
import { Route as HeaderLayoutExploreRouteImport } from './routes/_header-layout.explore'
import { Route as HeaderLayoutChatPreviewRouteImport } from './routes/_header-layout.chat-preview'
import { Route as HeaderLayoutChatRouteImport } from './routes/_header-layout.chat'
import { Route as HeaderLayoutAccountRouteImport } from './routes/_header-layout.account'
import { Route as HeaderLayoutAcceptTermsRouteImport } from './routes/_header-layout.accept-terms'
import { Route as DotwellKnownDidDotjsonRouteImport } from './routes/[.]well-known.did[.]json'
import { Route as HeaderLayoutMachinesIndexRouteImport } from './routes/_header-layout.machines.index'
import { Route as HeaderLayoutBlogIndexRouteImport } from './routes/_header-layout.blog.index'
import { Route as DocsHeaderLayoutDocsIndexRouteImport } from './routes/_docs-header-layout.docs.index'
import { Route as V1ChatCompletionsRouteImport } from './routes/v1.chat.completions'
import { Route as ApiXrpcDevDotcocoreDotproxyDotputRecordRouteImport } from './routes/api/xrpc/dev[.]cocore[.]proxy[.]putRecord'
import { Route as ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRouteImport } from './routes/api/xrpc/dev[.]cocore[.]proxy[.]deleteRecord'
import { Route as ApiXrpcDevDotcocoreDotproxyDotcreateRecordRouteImport } from './routes/api/xrpc/dev[.]cocore[.]proxy[.]createRecord'
import { Route as ApiXrpcDevDotcocoreDotinferenceDotdispatchRouteImport } from './routes/api/xrpc/dev[.]cocore[.]inference[.]dispatch'
import { Route as ApiXrpcDevDotcocoreDotdevicePairDotstartRouteImport } from './routes/api/xrpc/dev[.]cocore[.]devicePair[.]start'
import { Route as ApiXrpcDevDotcocoreDotdevicePairDotpollRouteImport } from './routes/api/xrpc/dev[.]cocore[.]devicePair[.]poll'
import { Route as ApiXrpcDevDotcocoreDotdevicePairDotconfirmRouteImport } from './routes/api/xrpc/dev[.]cocore[.]devicePair[.]confirm'
import { Route as ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRouteImport } from './routes/api/xrpc/dev[.]cocore[.]account[.]revokeApiKey'
import { Route as ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRouteImport } from './routes/api/xrpc/dev[.]cocore[.]account[.]listApiKeys'
import { Route as ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRouteImport } from './routes/api/xrpc/dev[.]cocore[.]account[.]deleteApiKey'
import { Route as ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRouteImport } from './routes/api/xrpc/dev[.]cocore[.]account[.]createApiKey'
import { Route as ApiV1ModelsRouteImport } from './routes/api/v1/models'
import { Route as ApiPdsPutRecordRouteImport } from './routes/api/pds/putRecord'
import { Route as ApiPdsDeleteRecordRouteImport } from './routes/api/pds/deleteRecord'
import { Route as ApiPdsCreateRecordRouteImport } from './routes/api/pds/createRecord'
import { Route as ApiInternalWipeEverythingRouteImport } from './routes/api/internal/wipe-everything'
import { Route as ApiInternalWipeRouteImport } from './routes/api/internal/wipe'
import { Route as ApiInternalMigrateSessionsToAppviewRouteImport } from './routes/api/internal/migrate-sessions-to-appview'
import { Route as ApiAgentWhoamiRouteImport } from './routes/api/agent.whoami'
import { Route as ApiAgentStatusRouteImport } from './routes/api/agent.status'
import { Route as ApiAgentHealthRouteImport } from './routes/api/agent.health'
import { Route as ApiAgentBugReportRouteImport } from './routes/api/agent.bug-report'
import { Route as HeaderLayoutUIdentifierRouteImport } from './routes/_header-layout.u.$identifier'
import { Route as HeaderLayoutMachinesRkeyRouteImport } from './routes/_header-layout.machines.$rkey'
import { Route as HeaderLayoutDevicesNewRouteImport } from './routes/_header-layout.devices.new'
import { Route as HeaderLayoutBlogSlugRouteImport } from './routes/_header-layout.blog.$slug'
import { Route as HeaderLayoutAdminDisputesRouteImport } from './routes/_header-layout.admin.disputes'
import { Route as DocsHeaderLayoutDocsSecurityRouteImport } from './routes/_docs-header-layout.docs.security'
import { Route as DocsHeaderLayoutDocsLexiconsRouteImport } from './routes/_docs-header-layout.docs.lexicons'
import { Route as DocsHeaderLayoutDocsInferenceRouteImport } from './routes/_docs-header-layout.docs.inference'
import { Route as DocsHeaderLayoutDocsCommunityToolsRouteImport } from './routes/_docs-header-layout.docs.community-tools'
import { Route as DocsHeaderLayoutDocsApiRouteImport } from './routes/_docs-header-layout.docs.api'
import { Route as DocsHeaderLayoutDocsInferenceIndexRouteImport } from './routes/_docs-header-layout.docs.inference.index'
import { Route as V1PrivateChatCompletionsRouteImport } from './routes/v1.private.chat.completions'
import { Route as ApiV1ChatCompletionsRouteImport } from './routes/api.v1.chat.completions'
import { Route as ApiInternalDisputesResolveRouteImport } from './routes/api/internal/disputes.resolve'
import { Route as ApiAuthAtprotoSignupRouteImport } from './routes/api.auth.atproto.signup'
import { Route as ApiAuthAtprotoMetadataDotjsonRouteImport } from './routes/api.auth.atproto.metadata[.]json'
import { Route as ApiAuthAtprotoJwksDotjsonRouteImport } from './routes/api.auth.atproto.jwks[.]json'
import { Route as ApiAuthAtprotoCallbackRouteImport } from './routes/api.auth.atproto.callback'
import { Route as ApiAuthAtprotoAuthorizeRouteImport } from './routes/api.auth.atproto.authorize'
import { Route as ApiAgentMdmRequestAttestationRouteImport } from './routes/api/agent.mdm.request-attestation'
import { Route as ApiAgentMdmPushAttestationRouteImport } from './routes/api/agent.mdm.push-attestation'
import { Route as ApiAgentMdmNanomdmWebhookRouteImport } from './routes/api/agent.mdm.nanomdm-webhook'
import { Route as ApiAgentMdmEnrollProfileRouteImport } from './routes/api/agent.mdm.enroll-profile'
import { Route as ApiAgentMdmAttestationChainRouteImport } from './routes/api/agent.mdm.attestation-chain'
import { Route as DocsHeaderLayoutDocsInferenceAuthenticationRouteImport } from './routes/_docs-header-layout.docs.inference.authentication'
import { Route as DocsHeaderLayoutDocsInferenceSlugRouteImport } from './routes/_docs-header-layout.docs.inference.$slug'
import { Route as ApiV1PrivateChatCompletionsRouteImport } from './routes/api.v1.private.chat.completions'

const OgDotpngRoute = OgDotpngRouteImport.update({
  id: '/og.png',
  path: '/og.png',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutRoute = HeaderLayoutRouteImport.update({
  id: '/_header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHeaderLayoutRoute = DocsHeaderLayoutRouteImport.update({
  id: '/_docs-header-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiconsIndexRoute = LexiconsIndexRouteImport.update({
  id: '/lexicons/',
  path: '/lexicons/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutIndexRoute = HeaderLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const XrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute =
  XrpcDevDotcocoreDotaccountDotrevokeApiKeyRouteImport.update({
    id: '/xrpc/dev.cocore.account.revokeApiKey',
    path: '/xrpc/dev.cocore.account.revokeApiKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const XrpcDevDotcocoreDotaccountDotlistApiKeysRoute =
  XrpcDevDotcocoreDotaccountDotlistApiKeysRouteImport.update({
    id: '/xrpc/dev.cocore.account.listApiKeys',
    path: '/xrpc/dev.cocore.account.listApiKeys',
    getParentRoute: () => rootRouteImport,
  } as any)
const XrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute =
  XrpcDevDotcocoreDotaccountDotdeleteApiKeyRouteImport.update({
    id: '/xrpc/dev.cocore.account.deleteApiKey',
    path: '/xrpc/dev.cocore.account.deleteApiKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const XrpcDevDotcocoreDotaccountDotcreateApiKeyRoute =
  XrpcDevDotcocoreDotaccountDotcreateApiKeyRouteImport.update({
    id: '/xrpc/dev.cocore.account.createApiKey',
    path: '/xrpc/dev.cocore.account.createApiKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1RecommendedModelsRoute = V1RecommendedModelsRouteImport.update({
  id: '/v1/recommended-models',
  path: '/v1/recommended-models',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ModelsRoute = V1ModelsRouteImport.update({
  id: '/v1/models',
  path: '/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LexiconsNsidRoute = LexiconsNsidRouteImport.update({
  id: '/lexicons/$nsid',
  path: '/lexicons/$nsid',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeDidDotjsonRoute = ExchangeDidDotjsonRouteImport.update({
  id: '/exchange/did.json',
  path: '/exchange/did.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentVersionRoute = AgentVersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => AgentRoute,
} as any)
const AgentUninstallRoute = AgentUninstallRouteImport.update({
  id: '/uninstall',
  path: '/uninstall',
  getParentRoute: () => AgentRoute,
} as any)
const AgentPolicyRoute = AgentPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => AgentRoute,
} as any)
const AgentInferenceRoute = AgentInferenceRouteImport.update({
  id: '/inference',
  path: '/inference',
  getParentRoute: () => AgentRoute,
} as any)
const AgentDlRoute = AgentDlRouteImport.update({
  id: '/dl',
  path: '/dl',
  getParentRoute: () => AgentRoute,
} as any)
const AgentBinaryHashesRoute = AgentBinaryHashesRouteImport.update({
  id: '/binary-hashes',
  path: '/binary-hashes',
  getParentRoute: () => AgentRoute,
} as any)
const AgentAppRoute = AgentAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AgentRoute,
} as any)
const HeaderLayoutTermsRoute = HeaderLayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutStartRoute = HeaderLayoutStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutPrivacyRoute = HeaderLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutModelsRoute = HeaderLayoutModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutLeaderboardRoute = HeaderLayoutLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutJobsRoute = HeaderLayoutJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutFriendsRoute = HeaderLayoutFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutExploreRoute = HeaderLayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutChatPreviewRoute = HeaderLayoutChatPreviewRouteImport.update({
  id: '/chat-preview',
  path: '/chat-preview',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutChatRoute = HeaderLayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAccountRoute = HeaderLayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAcceptTermsRoute = HeaderLayoutAcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const DotwellKnownDidDotjsonRoute = DotwellKnownDidDotjsonRouteImport.update({
  id: '/.well-known/did.json',
  path: '/.well-known/did.json',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutMachinesIndexRoute =
  HeaderLayoutMachinesIndexRouteImport.update({
    id: '/machines/',
    path: '/machines/',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutBlogIndexRoute = HeaderLayoutBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const DocsHeaderLayoutDocsIndexRoute =
  DocsHeaderLayoutDocsIndexRouteImport.update({
    id: '/docs/',
    path: '/docs/',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const V1ChatCompletionsRoute = V1ChatCompletionsRouteImport.update({
  id: '/v1/chat/completions',
  path: '/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXrpcDevDotcocoreDotproxyDotputRecordRoute =
  ApiXrpcDevDotcocoreDotproxyDotputRecordRouteImport.update({
    id: '/api/xrpc/dev.cocore.proxy.putRecord',
    path: '/api/xrpc/dev.cocore.proxy.putRecord',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRoute =
  ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRouteImport.update({
    id: '/api/xrpc/dev.cocore.proxy.deleteRecord',
    path: '/api/xrpc/dev.cocore.proxy.deleteRecord',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotproxyDotcreateRecordRoute =
  ApiXrpcDevDotcocoreDotproxyDotcreateRecordRouteImport.update({
    id: '/api/xrpc/dev.cocore.proxy.createRecord',
    path: '/api/xrpc/dev.cocore.proxy.createRecord',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotinferenceDotdispatchRoute =
  ApiXrpcDevDotcocoreDotinferenceDotdispatchRouteImport.update({
    id: '/api/xrpc/dev.cocore.inference.dispatch',
    path: '/api/xrpc/dev.cocore.inference.dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotdevicePairDotstartRoute =
  ApiXrpcDevDotcocoreDotdevicePairDotstartRouteImport.update({
    id: '/api/xrpc/dev.cocore.devicePair.start',
    path: '/api/xrpc/dev.cocore.devicePair.start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotdevicePairDotpollRoute =
  ApiXrpcDevDotcocoreDotdevicePairDotpollRouteImport.update({
    id: '/api/xrpc/dev.cocore.devicePair.poll',
    path: '/api/xrpc/dev.cocore.devicePair.poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotdevicePairDotconfirmRoute =
  ApiXrpcDevDotcocoreDotdevicePairDotconfirmRouteImport.update({
    id: '/api/xrpc/dev.cocore.devicePair.confirm',
    path: '/api/xrpc/dev.cocore.devicePair.confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute =
  ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRouteImport.update({
    id: '/api/xrpc/dev.cocore.account.revokeApiKey',
    path: '/api/xrpc/dev.cocore.account.revokeApiKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRoute =
  ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRouteImport.update({
    id: '/api/xrpc/dev.cocore.account.listApiKeys',
    path: '/api/xrpc/dev.cocore.account.listApiKeys',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute =
  ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRouteImport.update({
    id: '/api/xrpc/dev.cocore.account.deleteApiKey',
    path: '/api/xrpc/dev.cocore.account.deleteApiKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRoute =
  ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRouteImport.update({
    id: '/api/xrpc/dev.cocore.account.createApiKey',
    path: '/api/xrpc/dev.cocore.account.createApiKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ModelsRoute = ApiV1ModelsRouteImport.update({
  id: '/api/v1/models',
  path: '/api/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdsPutRecordRoute = ApiPdsPutRecordRouteImport.update({
  id: '/api/pds/putRecord',
  path: '/api/pds/putRecord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdsDeleteRecordRoute = ApiPdsDeleteRecordRouteImport.update({
  id: '/api/pds/deleteRecord',
  path: '/api/pds/deleteRecord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdsCreateRecordRoute = ApiPdsCreateRecordRouteImport.update({
  id: '/api/pds/createRecord',
  path: '/api/pds/createRecord',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalWipeEverythingRoute =
  ApiInternalWipeEverythingRouteImport.update({
    id: '/api/internal/wipe-everything',
    path: '/api/internal/wipe-everything',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalWipeRoute = ApiInternalWipeRouteImport.update({
  id: '/api/internal/wipe',
  path: '/api/internal/wipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalMigrateSessionsToAppviewRoute =
  ApiInternalMigrateSessionsToAppviewRouteImport.update({
    id: '/api/internal/migrate-sessions-to-appview',
    path: '/api/internal/migrate-sessions-to-appview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentWhoamiRoute = ApiAgentWhoamiRouteImport.update({
  id: '/api/agent/whoami',
  path: '/api/agent/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStatusRoute = ApiAgentStatusRouteImport.update({
  id: '/api/agent/status',
  path: '/api/agent/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentHealthRoute = ApiAgentHealthRouteImport.update({
  id: '/api/agent/health',
  path: '/api/agent/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentBugReportRoute = ApiAgentBugReportRouteImport.update({
  id: '/api/agent/bug-report',
  path: '/api/agent/bug-report',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderLayoutUIdentifierRoute = HeaderLayoutUIdentifierRouteImport.update({
  id: '/u/$identifier',
  path: '/u/$identifier',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutMachinesRkeyRoute =
  HeaderLayoutMachinesRkeyRouteImport.update({
    id: '/machines/$rkey',
    path: '/machines/$rkey',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const HeaderLayoutDevicesNewRoute = HeaderLayoutDevicesNewRouteImport.update({
  id: '/devices/new',
  path: '/devices/new',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutBlogSlugRoute = HeaderLayoutBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => HeaderLayoutRoute,
} as any)
const HeaderLayoutAdminDisputesRoute =
  HeaderLayoutAdminDisputesRouteImport.update({
    id: '/admin/disputes',
    path: '/admin/disputes',
    getParentRoute: () => HeaderLayoutRoute,
  } as any)
const DocsHeaderLayoutDocsSecurityRoute =
  DocsHeaderLayoutDocsSecurityRouteImport.update({
    id: '/docs/security',
    path: '/docs/security',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const DocsHeaderLayoutDocsLexiconsRoute =
  DocsHeaderLayoutDocsLexiconsRouteImport.update({
    id: '/docs/lexicons',
    path: '/docs/lexicons',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const DocsHeaderLayoutDocsInferenceRoute =
  DocsHeaderLayoutDocsInferenceRouteImport.update({
    id: '/docs/inference',
    path: '/docs/inference',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const DocsHeaderLayoutDocsCommunityToolsRoute =
  DocsHeaderLayoutDocsCommunityToolsRouteImport.update({
    id: '/docs/community-tools',
    path: '/docs/community-tools',
    getParentRoute: () => DocsHeaderLayoutRoute,
  } as any)
const DocsHeaderLayoutDocsApiRoute = DocsHeaderLayoutDocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => DocsHeaderLayoutRoute,
} as any)
const DocsHeaderLayoutDocsInferenceIndexRoute =
  DocsHeaderLayoutDocsInferenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocsHeaderLayoutDocsInferenceRoute,
  } as any)
const V1PrivateChatCompletionsRoute =
  V1PrivateChatCompletionsRouteImport.update({
    id: '/v1/private/chat/completions',
    path: '/v1/private/chat/completions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ChatCompletionsRoute = ApiV1ChatCompletionsRouteImport.update({
  id: '/api/v1/chat/completions',
  path: '/api/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalDisputesResolveRoute =
  ApiInternalDisputesResolveRouteImport.update({
    id: '/api/internal/disputes/resolve',
    path: '/api/internal/disputes/resolve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoSignupRoute = ApiAuthAtprotoSignupRouteImport.update({
  id: '/api/auth/atproto/signup',
  path: '/api/auth/atproto/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoMetadataDotjsonRoute =
  ApiAuthAtprotoMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/metadata.json',
    path: '/api/auth/atproto/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoJwksDotjsonRoute =
  ApiAuthAtprotoJwksDotjsonRouteImport.update({
    id: '/api/auth/atproto/jwks.json',
    path: '/api/auth/atproto/jwks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoCallbackRoute = ApiAuthAtprotoCallbackRouteImport.update({
  id: '/api/auth/atproto/callback',
  path: '/api/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoAuthorizeRoute = ApiAuthAtprotoAuthorizeRouteImport.update({
  id: '/api/auth/atproto/authorize',
  path: '/api/auth/atproto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMdmRequestAttestationRoute =
  ApiAgentMdmRequestAttestationRouteImport.update({
    id: '/api/agent/mdm/request-attestation',
    path: '/api/agent/mdm/request-attestation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentMdmPushAttestationRoute =
  ApiAgentMdmPushAttestationRouteImport.update({
    id: '/api/agent/mdm/push-attestation',
    path: '/api/agent/mdm/push-attestation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentMdmNanomdmWebhookRoute =
  ApiAgentMdmNanomdmWebhookRouteImport.update({
    id: '/api/agent/mdm/nanomdm-webhook',
    path: '/api/agent/mdm/nanomdm-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentMdmEnrollProfileRoute =
  ApiAgentMdmEnrollProfileRouteImport.update({
    id: '/api/agent/mdm/enroll-profile',
    path: '/api/agent/mdm/enroll-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentMdmAttestationChainRoute =
  ApiAgentMdmAttestationChainRouteImport.update({
    id: '/api/agent/mdm/attestation-chain',
    path: '/api/agent/mdm/attestation-chain',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsHeaderLayoutDocsInferenceAuthenticationRoute =
  DocsHeaderLayoutDocsInferenceAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => DocsHeaderLayoutDocsInferenceRoute,
  } as any)
const DocsHeaderLayoutDocsInferenceSlugRoute =
  DocsHeaderLayoutDocsInferenceSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => DocsHeaderLayoutDocsInferenceRoute,
  } as any)
const ApiV1PrivateChatCompletionsRoute =
  ApiV1PrivateChatCompletionsRouteImport.update({
    id: '/api/v1/private/chat/completions',
    path: '/api/v1/private/chat/completions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HeaderLayoutIndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/login': typeof LoginRoute
  '/og.png': typeof OgDotpngRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/accept-terms': typeof HeaderLayoutAcceptTermsRoute
  '/account': typeof HeaderLayoutAccountRoute
  '/chat': typeof HeaderLayoutChatRoute
  '/chat-preview': typeof HeaderLayoutChatPreviewRoute
  '/explore': typeof HeaderLayoutExploreRoute
  '/friends': typeof HeaderLayoutFriendsRoute
  '/jobs': typeof HeaderLayoutJobsRoute
  '/leaderboard': typeof HeaderLayoutLeaderboardRoute
  '/models': typeof HeaderLayoutModelsRoute
  '/privacy': typeof HeaderLayoutPrivacyRoute
  '/start': typeof HeaderLayoutStartRoute
  '/terms': typeof HeaderLayoutTermsRoute
  '/agent/app': typeof AgentAppRoute
  '/agent/binary-hashes': typeof AgentBinaryHashesRoute
  '/agent/dl': typeof AgentDlRoute
  '/agent/inference': typeof AgentInferenceRoute
  '/agent/policy': typeof AgentPolicyRoute
  '/agent/uninstall': typeof AgentUninstallRoute
  '/agent/version': typeof AgentVersionRoute
  '/exchange/did.json': typeof ExchangeDidDotjsonRoute
  '/lexicons/$nsid': typeof LexiconsNsidRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/recommended-models': typeof V1RecommendedModelsRoute
  '/xrpc/dev.cocore.account.createApiKey': typeof XrpcDevDotcocoreDotaccountDotcreateApiKeyRoute
  '/xrpc/dev.cocore.account.deleteApiKey': typeof XrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute
  '/xrpc/dev.cocore.account.listApiKeys': typeof XrpcDevDotcocoreDotaccountDotlistApiKeysRoute
  '/xrpc/dev.cocore.account.revokeApiKey': typeof XrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute
  '/lexicons/': typeof LexiconsIndexRoute
  '/docs/api': typeof DocsHeaderLayoutDocsApiRoute
  '/docs/community-tools': typeof DocsHeaderLayoutDocsCommunityToolsRoute
  '/docs/inference': typeof DocsHeaderLayoutDocsInferenceRouteWithChildren
  '/docs/lexicons': typeof DocsHeaderLayoutDocsLexiconsRoute
  '/docs/security': typeof DocsHeaderLayoutDocsSecurityRoute
  '/admin/disputes': typeof HeaderLayoutAdminDisputesRoute
  '/blog/$slug': typeof HeaderLayoutBlogSlugRoute
  '/devices/new': typeof HeaderLayoutDevicesNewRoute
  '/machines/$rkey': typeof HeaderLayoutMachinesRkeyRoute
  '/u/$identifier': typeof HeaderLayoutUIdentifierRoute
  '/api/agent/bug-report': typeof ApiAgentBugReportRoute
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/api/agent/status': typeof ApiAgentStatusRoute
  '/api/agent/whoami': typeof ApiAgentWhoamiRoute
  '/api/internal/migrate-sessions-to-appview': typeof ApiInternalMigrateSessionsToAppviewRoute
  '/api/internal/wipe': typeof ApiInternalWipeRoute
  '/api/internal/wipe-everything': typeof ApiInternalWipeEverythingRoute
  '/api/pds/createRecord': typeof ApiPdsCreateRecordRoute
  '/api/pds/deleteRecord': typeof ApiPdsDeleteRecordRoute
  '/api/pds/putRecord': typeof ApiPdsPutRecordRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/xrpc/dev.cocore.account.createApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRoute
  '/api/xrpc/dev.cocore.account.deleteApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute
  '/api/xrpc/dev.cocore.account.listApiKeys': typeof ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRoute
  '/api/xrpc/dev.cocore.account.revokeApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute
  '/api/xrpc/dev.cocore.devicePair.confirm': typeof ApiXrpcDevDotcocoreDotdevicePairDotconfirmRoute
  '/api/xrpc/dev.cocore.devicePair.poll': typeof ApiXrpcDevDotcocoreDotdevicePairDotpollRoute
  '/api/xrpc/dev.cocore.devicePair.start': typeof ApiXrpcDevDotcocoreDotdevicePairDotstartRoute
  '/api/xrpc/dev.cocore.inference.dispatch': typeof ApiXrpcDevDotcocoreDotinferenceDotdispatchRoute
  '/api/xrpc/dev.cocore.proxy.createRecord': typeof ApiXrpcDevDotcocoreDotproxyDotcreateRecordRoute
  '/api/xrpc/dev.cocore.proxy.deleteRecord': typeof ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRoute
  '/api/xrpc/dev.cocore.proxy.putRecord': typeof ApiXrpcDevDotcocoreDotproxyDotputRecordRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/docs/': typeof DocsHeaderLayoutDocsIndexRoute
  '/blog/': typeof HeaderLayoutBlogIndexRoute
  '/machines/': typeof HeaderLayoutMachinesIndexRoute
  '/docs/inference/$slug': typeof DocsHeaderLayoutDocsInferenceSlugRoute
  '/docs/inference/authentication': typeof DocsHeaderLayoutDocsInferenceAuthenticationRoute
  '/api/agent/mdm/attestation-chain': typeof ApiAgentMdmAttestationChainRoute
  '/api/agent/mdm/enroll-profile': typeof ApiAgentMdmEnrollProfileRoute
  '/api/agent/mdm/nanomdm-webhook': typeof ApiAgentMdmNanomdmWebhookRoute
  '/api/agent/mdm/push-attestation': typeof ApiAgentMdmPushAttestationRoute
  '/api/agent/mdm/request-attestation': typeof ApiAgentMdmRequestAttestationRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/api/internal/disputes/resolve': typeof ApiInternalDisputesResolveRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
  '/v1/private/chat/completions': typeof V1PrivateChatCompletionsRoute
  '/docs/inference/': typeof DocsHeaderLayoutDocsInferenceIndexRoute
  '/api/v1/private/chat/completions': typeof ApiV1PrivateChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/': typeof HeaderLayoutIndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/login': typeof LoginRoute
  '/og.png': typeof OgDotpngRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/accept-terms': typeof HeaderLayoutAcceptTermsRoute
  '/account': typeof HeaderLayoutAccountRoute
  '/chat': typeof HeaderLayoutChatRoute
  '/chat-preview': typeof HeaderLayoutChatPreviewRoute
  '/explore': typeof HeaderLayoutExploreRoute
  '/friends': typeof HeaderLayoutFriendsRoute
  '/jobs': typeof HeaderLayoutJobsRoute
  '/leaderboard': typeof HeaderLayoutLeaderboardRoute
  '/models': typeof HeaderLayoutModelsRoute
  '/privacy': typeof HeaderLayoutPrivacyRoute
  '/start': typeof HeaderLayoutStartRoute
  '/terms': typeof HeaderLayoutTermsRoute
  '/agent/app': typeof AgentAppRoute
  '/agent/binary-hashes': typeof AgentBinaryHashesRoute
  '/agent/dl': typeof AgentDlRoute
  '/agent/inference': typeof AgentInferenceRoute
  '/agent/policy': typeof AgentPolicyRoute
  '/agent/uninstall': typeof AgentUninstallRoute
  '/agent/version': typeof AgentVersionRoute
  '/exchange/did.json': typeof ExchangeDidDotjsonRoute
  '/lexicons/$nsid': typeof LexiconsNsidRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/recommended-models': typeof V1RecommendedModelsRoute
  '/xrpc/dev.cocore.account.createApiKey': typeof XrpcDevDotcocoreDotaccountDotcreateApiKeyRoute
  '/xrpc/dev.cocore.account.deleteApiKey': typeof XrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute
  '/xrpc/dev.cocore.account.listApiKeys': typeof XrpcDevDotcocoreDotaccountDotlistApiKeysRoute
  '/xrpc/dev.cocore.account.revokeApiKey': typeof XrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute
  '/lexicons': typeof LexiconsIndexRoute
  '/docs/api': typeof DocsHeaderLayoutDocsApiRoute
  '/docs/community-tools': typeof DocsHeaderLayoutDocsCommunityToolsRoute
  '/docs/lexicons': typeof DocsHeaderLayoutDocsLexiconsRoute
  '/docs/security': typeof DocsHeaderLayoutDocsSecurityRoute
  '/admin/disputes': typeof HeaderLayoutAdminDisputesRoute
  '/blog/$slug': typeof HeaderLayoutBlogSlugRoute
  '/devices/new': typeof HeaderLayoutDevicesNewRoute
  '/machines/$rkey': typeof HeaderLayoutMachinesRkeyRoute
  '/u/$identifier': typeof HeaderLayoutUIdentifierRoute
  '/api/agent/bug-report': typeof ApiAgentBugReportRoute
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/api/agent/status': typeof ApiAgentStatusRoute
  '/api/agent/whoami': typeof ApiAgentWhoamiRoute
  '/api/internal/migrate-sessions-to-appview': typeof ApiInternalMigrateSessionsToAppviewRoute
  '/api/internal/wipe': typeof ApiInternalWipeRoute
  '/api/internal/wipe-everything': typeof ApiInternalWipeEverythingRoute
  '/api/pds/createRecord': typeof ApiPdsCreateRecordRoute
  '/api/pds/deleteRecord': typeof ApiPdsDeleteRecordRoute
  '/api/pds/putRecord': typeof ApiPdsPutRecordRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/xrpc/dev.cocore.account.createApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRoute
  '/api/xrpc/dev.cocore.account.deleteApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute
  '/api/xrpc/dev.cocore.account.listApiKeys': typeof ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRoute
  '/api/xrpc/dev.cocore.account.revokeApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute
  '/api/xrpc/dev.cocore.devicePair.confirm': typeof ApiXrpcDevDotcocoreDotdevicePairDotconfirmRoute
  '/api/xrpc/dev.cocore.devicePair.poll': typeof ApiXrpcDevDotcocoreDotdevicePairDotpollRoute
  '/api/xrpc/dev.cocore.devicePair.start': typeof ApiXrpcDevDotcocoreDotdevicePairDotstartRoute
  '/api/xrpc/dev.cocore.inference.dispatch': typeof ApiXrpcDevDotcocoreDotinferenceDotdispatchRoute
  '/api/xrpc/dev.cocore.proxy.createRecord': typeof ApiXrpcDevDotcocoreDotproxyDotcreateRecordRoute
  '/api/xrpc/dev.cocore.proxy.deleteRecord': typeof ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRoute
  '/api/xrpc/dev.cocore.proxy.putRecord': typeof ApiXrpcDevDotcocoreDotproxyDotputRecordRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/docs': typeof DocsHeaderLayoutDocsIndexRoute
  '/blog': typeof HeaderLayoutBlogIndexRoute
  '/machines': typeof HeaderLayoutMachinesIndexRoute
  '/docs/inference/$slug': typeof DocsHeaderLayoutDocsInferenceSlugRoute
  '/docs/inference/authentication': typeof DocsHeaderLayoutDocsInferenceAuthenticationRoute
  '/api/agent/mdm/attestation-chain': typeof ApiAgentMdmAttestationChainRoute
  '/api/agent/mdm/enroll-profile': typeof ApiAgentMdmEnrollProfileRoute
  '/api/agent/mdm/nanomdm-webhook': typeof ApiAgentMdmNanomdmWebhookRoute
  '/api/agent/mdm/push-attestation': typeof ApiAgentMdmPushAttestationRoute
  '/api/agent/mdm/request-attestation': typeof ApiAgentMdmRequestAttestationRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/api/internal/disputes/resolve': typeof ApiInternalDisputesResolveRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
  '/v1/private/chat/completions': typeof V1PrivateChatCompletionsRoute
  '/docs/inference': typeof DocsHeaderLayoutDocsInferenceIndexRoute
  '/api/v1/private/chat/completions': typeof ApiV1PrivateChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_docs-header-layout': typeof DocsHeaderLayoutRouteWithChildren
  '/_header-layout': typeof HeaderLayoutRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/login': typeof LoginRoute
  '/og.png': typeof OgDotpngRoute
  '/.well-known/did.json': typeof DotwellKnownDidDotjsonRoute
  '/_header-layout/accept-terms': typeof HeaderLayoutAcceptTermsRoute
  '/_header-layout/account': typeof HeaderLayoutAccountRoute
  '/_header-layout/chat': typeof HeaderLayoutChatRoute
  '/_header-layout/chat-preview': typeof HeaderLayoutChatPreviewRoute
  '/_header-layout/explore': typeof HeaderLayoutExploreRoute
  '/_header-layout/friends': typeof HeaderLayoutFriendsRoute
  '/_header-layout/jobs': typeof HeaderLayoutJobsRoute
  '/_header-layout/leaderboard': typeof HeaderLayoutLeaderboardRoute
  '/_header-layout/models': typeof HeaderLayoutModelsRoute
  '/_header-layout/privacy': typeof HeaderLayoutPrivacyRoute
  '/_header-layout/start': typeof HeaderLayoutStartRoute
  '/_header-layout/terms': typeof HeaderLayoutTermsRoute
  '/agent/app': typeof AgentAppRoute
  '/agent/binary-hashes': typeof AgentBinaryHashesRoute
  '/agent/dl': typeof AgentDlRoute
  '/agent/inference': typeof AgentInferenceRoute
  '/agent/policy': typeof AgentPolicyRoute
  '/agent/uninstall': typeof AgentUninstallRoute
  '/agent/version': typeof AgentVersionRoute
  '/exchange/did.json': typeof ExchangeDidDotjsonRoute
  '/lexicons/$nsid': typeof LexiconsNsidRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/recommended-models': typeof V1RecommendedModelsRoute
  '/xrpc/dev.cocore.account.createApiKey': typeof XrpcDevDotcocoreDotaccountDotcreateApiKeyRoute
  '/xrpc/dev.cocore.account.deleteApiKey': typeof XrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute
  '/xrpc/dev.cocore.account.listApiKeys': typeof XrpcDevDotcocoreDotaccountDotlistApiKeysRoute
  '/xrpc/dev.cocore.account.revokeApiKey': typeof XrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute
  '/_header-layout/': typeof HeaderLayoutIndexRoute
  '/lexicons/': typeof LexiconsIndexRoute
  '/_docs-header-layout/docs/api': typeof DocsHeaderLayoutDocsApiRoute
  '/_docs-header-layout/docs/community-tools': typeof DocsHeaderLayoutDocsCommunityToolsRoute
  '/_docs-header-layout/docs/inference': typeof DocsHeaderLayoutDocsInferenceRouteWithChildren
  '/_docs-header-layout/docs/lexicons': typeof DocsHeaderLayoutDocsLexiconsRoute
  '/_docs-header-layout/docs/security': typeof DocsHeaderLayoutDocsSecurityRoute
  '/_header-layout/admin/disputes': typeof HeaderLayoutAdminDisputesRoute
  '/_header-layout/blog/$slug': typeof HeaderLayoutBlogSlugRoute
  '/_header-layout/devices/new': typeof HeaderLayoutDevicesNewRoute
  '/_header-layout/machines/$rkey': typeof HeaderLayoutMachinesRkeyRoute
  '/_header-layout/u/$identifier': typeof HeaderLayoutUIdentifierRoute
  '/api/agent/bug-report': typeof ApiAgentBugReportRoute
  '/api/agent/health': typeof ApiAgentHealthRoute
  '/api/agent/status': typeof ApiAgentStatusRoute
  '/api/agent/whoami': typeof ApiAgentWhoamiRoute
  '/api/internal/migrate-sessions-to-appview': typeof ApiInternalMigrateSessionsToAppviewRoute
  '/api/internal/wipe': typeof ApiInternalWipeRoute
  '/api/internal/wipe-everything': typeof ApiInternalWipeEverythingRoute
  '/api/pds/createRecord': typeof ApiPdsCreateRecordRoute
  '/api/pds/deleteRecord': typeof ApiPdsDeleteRecordRoute
  '/api/pds/putRecord': typeof ApiPdsPutRecordRoute
  '/api/v1/models': typeof ApiV1ModelsRoute
  '/api/xrpc/dev.cocore.account.createApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRoute
  '/api/xrpc/dev.cocore.account.deleteApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute
  '/api/xrpc/dev.cocore.account.listApiKeys': typeof ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRoute
  '/api/xrpc/dev.cocore.account.revokeApiKey': typeof ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute
  '/api/xrpc/dev.cocore.devicePair.confirm': typeof ApiXrpcDevDotcocoreDotdevicePairDotconfirmRoute
  '/api/xrpc/dev.cocore.devicePair.poll': typeof ApiXrpcDevDotcocoreDotdevicePairDotpollRoute
  '/api/xrpc/dev.cocore.devicePair.start': typeof ApiXrpcDevDotcocoreDotdevicePairDotstartRoute
  '/api/xrpc/dev.cocore.inference.dispatch': typeof ApiXrpcDevDotcocoreDotinferenceDotdispatchRoute
  '/api/xrpc/dev.cocore.proxy.createRecord': typeof ApiXrpcDevDotcocoreDotproxyDotcreateRecordRoute
  '/api/xrpc/dev.cocore.proxy.deleteRecord': typeof ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRoute
  '/api/xrpc/dev.cocore.proxy.putRecord': typeof ApiXrpcDevDotcocoreDotproxyDotputRecordRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
  '/_docs-header-layout/docs/': typeof DocsHeaderLayoutDocsIndexRoute
  '/_header-layout/blog/': typeof HeaderLayoutBlogIndexRoute
  '/_header-layout/machines/': typeof HeaderLayoutMachinesIndexRoute
  '/_docs-header-layout/docs/inference/$slug': typeof DocsHeaderLayoutDocsInferenceSlugRoute
  '/_docs-header-layout/docs/inference/authentication': typeof DocsHeaderLayoutDocsInferenceAuthenticationRoute
  '/api/agent/mdm/attestation-chain': typeof ApiAgentMdmAttestationChainRoute
  '/api/agent/mdm/enroll-profile': typeof ApiAgentMdmEnrollProfileRoute
  '/api/agent/mdm/nanomdm-webhook': typeof ApiAgentMdmNanomdmWebhookRoute
  '/api/agent/mdm/push-attestation': typeof ApiAgentMdmPushAttestationRoute
  '/api/agent/mdm/request-attestation': typeof ApiAgentMdmRequestAttestationRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/atproto/signup': typeof ApiAuthAtprotoSignupRoute
  '/api/internal/disputes/resolve': typeof ApiInternalDisputesResolveRoute
  '/api/v1/chat/completions': typeof ApiV1ChatCompletionsRoute
  '/v1/private/chat/completions': typeof V1PrivateChatCompletionsRoute
  '/_docs-header-layout/docs/inference/': typeof DocsHeaderLayoutDocsInferenceIndexRoute
  '/api/v1/private/chat/completions': typeof ApiV1PrivateChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/login'
    | '/og.png'
    | '/.well-known/did.json'
    | '/accept-terms'
    | '/account'
    | '/chat'
    | '/chat-preview'
    | '/explore'
    | '/friends'
    | '/jobs'
    | '/leaderboard'
    | '/models'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/agent/app'
    | '/agent/binary-hashes'
    | '/agent/dl'
    | '/agent/inference'
    | '/agent/policy'
    | '/agent/uninstall'
    | '/agent/version'
    | '/exchange/did.json'
    | '/lexicons/$nsid'
    | '/v1/models'
    | '/v1/recommended-models'
    | '/xrpc/dev.cocore.account.createApiKey'
    | '/xrpc/dev.cocore.account.deleteApiKey'
    | '/xrpc/dev.cocore.account.listApiKeys'
    | '/xrpc/dev.cocore.account.revokeApiKey'
    | '/lexicons/'
    | '/docs/api'
    | '/docs/community-tools'
    | '/docs/inference'
    | '/docs/lexicons'
    | '/docs/security'
    | '/admin/disputes'
    | '/blog/$slug'
    | '/devices/new'
    | '/machines/$rkey'
    | '/u/$identifier'
    | '/api/agent/bug-report'
    | '/api/agent/health'
    | '/api/agent/status'
    | '/api/agent/whoami'
    | '/api/internal/migrate-sessions-to-appview'
    | '/api/internal/wipe'
    | '/api/internal/wipe-everything'
    | '/api/pds/createRecord'
    | '/api/pds/deleteRecord'
    | '/api/pds/putRecord'
    | '/api/v1/models'
    | '/api/xrpc/dev.cocore.account.createApiKey'
    | '/api/xrpc/dev.cocore.account.deleteApiKey'
    | '/api/xrpc/dev.cocore.account.listApiKeys'
    | '/api/xrpc/dev.cocore.account.revokeApiKey'
    | '/api/xrpc/dev.cocore.devicePair.confirm'
    | '/api/xrpc/dev.cocore.devicePair.poll'
    | '/api/xrpc/dev.cocore.devicePair.start'
    | '/api/xrpc/dev.cocore.inference.dispatch'
    | '/api/xrpc/dev.cocore.proxy.createRecord'
    | '/api/xrpc/dev.cocore.proxy.deleteRecord'
    | '/api/xrpc/dev.cocore.proxy.putRecord'
    | '/v1/chat/completions'
    | '/docs/'
    | '/blog/'
    | '/machines/'
    | '/docs/inference/$slug'
    | '/docs/inference/authentication'
    | '/api/agent/mdm/attestation-chain'
    | '/api/agent/mdm/enroll-profile'
    | '/api/agent/mdm/nanomdm-webhook'
    | '/api/agent/mdm/push-attestation'
    | '/api/agent/mdm/request-attestation'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/api/internal/disputes/resolve'
    | '/api/v1/chat/completions'
    | '/v1/private/chat/completions'
    | '/docs/inference/'
    | '/api/v1/private/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/login'
    | '/og.png'
    | '/.well-known/did.json'
    | '/accept-terms'
    | '/account'
    | '/chat'
    | '/chat-preview'
    | '/explore'
    | '/friends'
    | '/jobs'
    | '/leaderboard'
    | '/models'
    | '/privacy'
    | '/start'
    | '/terms'
    | '/agent/app'
    | '/agent/binary-hashes'
    | '/agent/dl'
    | '/agent/inference'
    | '/agent/policy'
    | '/agent/uninstall'
    | '/agent/version'
    | '/exchange/did.json'
    | '/lexicons/$nsid'
    | '/v1/models'
    | '/v1/recommended-models'
    | '/xrpc/dev.cocore.account.createApiKey'
    | '/xrpc/dev.cocore.account.deleteApiKey'
    | '/xrpc/dev.cocore.account.listApiKeys'
    | '/xrpc/dev.cocore.account.revokeApiKey'
    | '/lexicons'
    | '/docs/api'
    | '/docs/community-tools'
    | '/docs/lexicons'
    | '/docs/security'
    | '/admin/disputes'
    | '/blog/$slug'
    | '/devices/new'
    | '/machines/$rkey'
    | '/u/$identifier'
    | '/api/agent/bug-report'
    | '/api/agent/health'
    | '/api/agent/status'
    | '/api/agent/whoami'
    | '/api/internal/migrate-sessions-to-appview'
    | '/api/internal/wipe'
    | '/api/internal/wipe-everything'
    | '/api/pds/createRecord'
    | '/api/pds/deleteRecord'
    | '/api/pds/putRecord'
    | '/api/v1/models'
    | '/api/xrpc/dev.cocore.account.createApiKey'
    | '/api/xrpc/dev.cocore.account.deleteApiKey'
    | '/api/xrpc/dev.cocore.account.listApiKeys'
    | '/api/xrpc/dev.cocore.account.revokeApiKey'
    | '/api/xrpc/dev.cocore.devicePair.confirm'
    | '/api/xrpc/dev.cocore.devicePair.poll'
    | '/api/xrpc/dev.cocore.devicePair.start'
    | '/api/xrpc/dev.cocore.inference.dispatch'
    | '/api/xrpc/dev.cocore.proxy.createRecord'
    | '/api/xrpc/dev.cocore.proxy.deleteRecord'
    | '/api/xrpc/dev.cocore.proxy.putRecord'
    | '/v1/chat/completions'
    | '/docs'
    | '/blog'
    | '/machines'
    | '/docs/inference/$slug'
    | '/docs/inference/authentication'
    | '/api/agent/mdm/attestation-chain'
    | '/api/agent/mdm/enroll-profile'
    | '/api/agent/mdm/nanomdm-webhook'
    | '/api/agent/mdm/push-attestation'
    | '/api/agent/mdm/request-attestation'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/api/internal/disputes/resolve'
    | '/api/v1/chat/completions'
    | '/v1/private/chat/completions'
    | '/docs/inference'
    | '/api/v1/private/chat/completions'
  id:
    | '__root__'
    | '/_docs-header-layout'
    | '/_header-layout'
    | '/agent'
    | '/login'
    | '/og.png'
    | '/.well-known/did.json'
    | '/_header-layout/accept-terms'
    | '/_header-layout/account'
    | '/_header-layout/chat'
    | '/_header-layout/chat-preview'
    | '/_header-layout/explore'
    | '/_header-layout/friends'
    | '/_header-layout/jobs'
    | '/_header-layout/leaderboard'
    | '/_header-layout/models'
    | '/_header-layout/privacy'
    | '/_header-layout/start'
    | '/_header-layout/terms'
    | '/agent/app'
    | '/agent/binary-hashes'
    | '/agent/dl'
    | '/agent/inference'
    | '/agent/policy'
    | '/agent/uninstall'
    | '/agent/version'
    | '/exchange/did.json'
    | '/lexicons/$nsid'
    | '/v1/models'
    | '/v1/recommended-models'
    | '/xrpc/dev.cocore.account.createApiKey'
    | '/xrpc/dev.cocore.account.deleteApiKey'
    | '/xrpc/dev.cocore.account.listApiKeys'
    | '/xrpc/dev.cocore.account.revokeApiKey'
    | '/_header-layout/'
    | '/lexicons/'
    | '/_docs-header-layout/docs/api'
    | '/_docs-header-layout/docs/community-tools'
    | '/_docs-header-layout/docs/inference'
    | '/_docs-header-layout/docs/lexicons'
    | '/_docs-header-layout/docs/security'
    | '/_header-layout/admin/disputes'
    | '/_header-layout/blog/$slug'
    | '/_header-layout/devices/new'
    | '/_header-layout/machines/$rkey'
    | '/_header-layout/u/$identifier'
    | '/api/agent/bug-report'
    | '/api/agent/health'
    | '/api/agent/status'
    | '/api/agent/whoami'
    | '/api/internal/migrate-sessions-to-appview'
    | '/api/internal/wipe'
    | '/api/internal/wipe-everything'
    | '/api/pds/createRecord'
    | '/api/pds/deleteRecord'
    | '/api/pds/putRecord'
    | '/api/v1/models'
    | '/api/xrpc/dev.cocore.account.createApiKey'
    | '/api/xrpc/dev.cocore.account.deleteApiKey'
    | '/api/xrpc/dev.cocore.account.listApiKeys'
    | '/api/xrpc/dev.cocore.account.revokeApiKey'
    | '/api/xrpc/dev.cocore.devicePair.confirm'
    | '/api/xrpc/dev.cocore.devicePair.poll'
    | '/api/xrpc/dev.cocore.devicePair.start'
    | '/api/xrpc/dev.cocore.inference.dispatch'
    | '/api/xrpc/dev.cocore.proxy.createRecord'
    | '/api/xrpc/dev.cocore.proxy.deleteRecord'
    | '/api/xrpc/dev.cocore.proxy.putRecord'
    | '/v1/chat/completions'
    | '/_docs-header-layout/docs/'
    | '/_header-layout/blog/'
    | '/_header-layout/machines/'
    | '/_docs-header-layout/docs/inference/$slug'
    | '/_docs-header-layout/docs/inference/authentication'
    | '/api/agent/mdm/attestation-chain'
    | '/api/agent/mdm/enroll-profile'
    | '/api/agent/mdm/nanomdm-webhook'
    | '/api/agent/mdm/push-attestation'
    | '/api/agent/mdm/request-attestation'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/atproto/signup'
    | '/api/internal/disputes/resolve'
    | '/api/v1/chat/completions'
    | '/v1/private/chat/completions'
    | '/_docs-header-layout/docs/inference/'
    | '/api/v1/private/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DocsHeaderLayoutRoute: typeof DocsHeaderLayoutRouteWithChildren
  HeaderLayoutRoute: typeof HeaderLayoutRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  LoginRoute: typeof LoginRoute
  OgDotpngRoute: typeof OgDotpngRoute
  DotwellKnownDidDotjsonRoute: typeof DotwellKnownDidDotjsonRoute
  ExchangeDidDotjsonRoute: typeof ExchangeDidDotjsonRoute
  LexiconsNsidRoute: typeof LexiconsNsidRoute
  V1ModelsRoute: typeof V1ModelsRoute
  V1RecommendedModelsRoute: typeof V1RecommendedModelsRoute
  XrpcDevDotcocoreDotaccountDotcreateApiKeyRoute: typeof XrpcDevDotcocoreDotaccountDotcreateApiKeyRoute
  XrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute: typeof XrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute
  XrpcDevDotcocoreDotaccountDotlistApiKeysRoute: typeof XrpcDevDotcocoreDotaccountDotlistApiKeysRoute
  XrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute: typeof XrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute
  LexiconsIndexRoute: typeof LexiconsIndexRoute
  ApiAgentBugReportRoute: typeof ApiAgentBugReportRoute
  ApiAgentHealthRoute: typeof ApiAgentHealthRoute
  ApiAgentStatusRoute: typeof ApiAgentStatusRoute
  ApiAgentWhoamiRoute: typeof ApiAgentWhoamiRoute
  ApiInternalMigrateSessionsToAppviewRoute: typeof ApiInternalMigrateSessionsToAppviewRoute
  ApiInternalWipeRoute: typeof ApiInternalWipeRoute
  ApiInternalWipeEverythingRoute: typeof ApiInternalWipeEverythingRoute
  ApiPdsCreateRecordRoute: typeof ApiPdsCreateRecordRoute
  ApiPdsDeleteRecordRoute: typeof ApiPdsDeleteRecordRoute
  ApiPdsPutRecordRoute: typeof ApiPdsPutRecordRoute
  ApiV1ModelsRoute: typeof ApiV1ModelsRoute
  ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRoute: typeof ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRoute
  ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute: typeof ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute
  ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRoute: typeof ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRoute
  ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute: typeof ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute
  ApiXrpcDevDotcocoreDotdevicePairDotconfirmRoute: typeof ApiXrpcDevDotcocoreDotdevicePairDotconfirmRoute
  ApiXrpcDevDotcocoreDotdevicePairDotpollRoute: typeof ApiXrpcDevDotcocoreDotdevicePairDotpollRoute
  ApiXrpcDevDotcocoreDotdevicePairDotstartRoute: typeof ApiXrpcDevDotcocoreDotdevicePairDotstartRoute
  ApiXrpcDevDotcocoreDotinferenceDotdispatchRoute: typeof ApiXrpcDevDotcocoreDotinferenceDotdispatchRoute
  ApiXrpcDevDotcocoreDotproxyDotcreateRecordRoute: typeof ApiXrpcDevDotcocoreDotproxyDotcreateRecordRoute
  ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRoute: typeof ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRoute
  ApiXrpcDevDotcocoreDotproxyDotputRecordRoute: typeof ApiXrpcDevDotcocoreDotproxyDotputRecordRoute
  V1ChatCompletionsRoute: typeof V1ChatCompletionsRoute
  ApiAgentMdmAttestationChainRoute: typeof ApiAgentMdmAttestationChainRoute
  ApiAgentMdmEnrollProfileRoute: typeof ApiAgentMdmEnrollProfileRoute
  ApiAgentMdmNanomdmWebhookRoute: typeof ApiAgentMdmNanomdmWebhookRoute
  ApiAgentMdmPushAttestationRoute: typeof ApiAgentMdmPushAttestationRoute
  ApiAgentMdmRequestAttestationRoute: typeof ApiAgentMdmRequestAttestationRoute
  ApiAuthAtprotoAuthorizeRoute: typeof ApiAuthAtprotoAuthorizeRoute
  ApiAuthAtprotoCallbackRoute: typeof ApiAuthAtprotoCallbackRoute
  ApiAuthAtprotoJwksDotjsonRoute: typeof ApiAuthAtprotoJwksDotjsonRoute
  ApiAuthAtprotoMetadataDotjsonRoute: typeof ApiAuthAtprotoMetadataDotjsonRoute
  ApiAuthAtprotoSignupRoute: typeof ApiAuthAtprotoSignupRoute
  ApiInternalDisputesResolveRoute: typeof ApiInternalDisputesResolveRoute
  ApiV1ChatCompletionsRoute: typeof ApiV1ChatCompletionsRoute
  V1PrivateChatCompletionsRoute: typeof V1PrivateChatCompletionsRoute
  ApiV1PrivateChatCompletionsRoute: typeof ApiV1PrivateChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og.png': {
      id: '/og.png'
      path: '/og.png'
      fullPath: '/og.png'
      preLoaderRoute: typeof OgDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout': {
      id: '/_header-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs-header-layout': {
      id: '/_docs-header-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsHeaderLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexicons/': {
      id: '/lexicons/'
      path: '/lexicons'
      fullPath: '/lexicons/'
      preLoaderRoute: typeof LexiconsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/': {
      id: '/_header-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HeaderLayoutIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/xrpc/dev.cocore.account.revokeApiKey': {
      id: '/xrpc/dev.cocore.account.revokeApiKey'
      path: '/xrpc/dev.cocore.account.revokeApiKey'
      fullPath: '/xrpc/dev.cocore.account.revokeApiKey'
      preLoaderRoute: typeof XrpcDevDotcocoreDotaccountDotrevokeApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/dev.cocore.account.listApiKeys': {
      id: '/xrpc/dev.cocore.account.listApiKeys'
      path: '/xrpc/dev.cocore.account.listApiKeys'
      fullPath: '/xrpc/dev.cocore.account.listApiKeys'
      preLoaderRoute: typeof XrpcDevDotcocoreDotaccountDotlistApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/dev.cocore.account.deleteApiKey': {
      id: '/xrpc/dev.cocore.account.deleteApiKey'
      path: '/xrpc/dev.cocore.account.deleteApiKey'
      fullPath: '/xrpc/dev.cocore.account.deleteApiKey'
      preLoaderRoute: typeof XrpcDevDotcocoreDotaccountDotdeleteApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xrpc/dev.cocore.account.createApiKey': {
      id: '/xrpc/dev.cocore.account.createApiKey'
      path: '/xrpc/dev.cocore.account.createApiKey'
      fullPath: '/xrpc/dev.cocore.account.createApiKey'
      preLoaderRoute: typeof XrpcDevDotcocoreDotaccountDotcreateApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/recommended-models': {
      id: '/v1/recommended-models'
      path: '/v1/recommended-models'
      fullPath: '/v1/recommended-models'
      preLoaderRoute: typeof V1RecommendedModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/models': {
      id: '/v1/models'
      path: '/v1/models'
      fullPath: '/v1/models'
      preLoaderRoute: typeof V1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lexicons/$nsid': {
      id: '/lexicons/$nsid'
      path: '/lexicons/$nsid'
      fullPath: '/lexicons/$nsid'
      preLoaderRoute: typeof LexiconsNsidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange/did.json': {
      id: '/exchange/did.json'
      path: '/exchange/did.json'
      fullPath: '/exchange/did.json'
      preLoaderRoute: typeof ExchangeDidDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/version': {
      id: '/agent/version'
      path: '/version'
      fullPath: '/agent/version'
      preLoaderRoute: typeof AgentVersionRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/uninstall': {
      id: '/agent/uninstall'
      path: '/uninstall'
      fullPath: '/agent/uninstall'
      preLoaderRoute: typeof AgentUninstallRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/policy': {
      id: '/agent/policy'
      path: '/policy'
      fullPath: '/agent/policy'
      preLoaderRoute: typeof AgentPolicyRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/inference': {
      id: '/agent/inference'
      path: '/inference'
      fullPath: '/agent/inference'
      preLoaderRoute: typeof AgentInferenceRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/dl': {
      id: '/agent/dl'
      path: '/dl'
      fullPath: '/agent/dl'
      preLoaderRoute: typeof AgentDlRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/binary-hashes': {
      id: '/agent/binary-hashes'
      path: '/binary-hashes'
      fullPath: '/agent/binary-hashes'
      preLoaderRoute: typeof AgentBinaryHashesRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/app': {
      id: '/agent/app'
      path: '/app'
      fullPath: '/agent/app'
      preLoaderRoute: typeof AgentAppRouteImport
      parentRoute: typeof AgentRoute
    }
    '/_header-layout/terms': {
      id: '/_header-layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof HeaderLayoutTermsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/start': {
      id: '/_header-layout/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof HeaderLayoutStartRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/privacy': {
      id: '/_header-layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof HeaderLayoutPrivacyRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/models': {
      id: '/_header-layout/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof HeaderLayoutModelsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/leaderboard': {
      id: '/_header-layout/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof HeaderLayoutLeaderboardRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/jobs': {
      id: '/_header-layout/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof HeaderLayoutJobsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/friends': {
      id: '/_header-layout/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof HeaderLayoutFriendsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/explore': {
      id: '/_header-layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof HeaderLayoutExploreRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/chat-preview': {
      id: '/_header-layout/chat-preview'
      path: '/chat-preview'
      fullPath: '/chat-preview'
      preLoaderRoute: typeof HeaderLayoutChatPreviewRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/chat': {
      id: '/_header-layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof HeaderLayoutChatRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/account': {
      id: '/_header-layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof HeaderLayoutAccountRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/accept-terms': {
      id: '/_header-layout/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof HeaderLayoutAcceptTermsRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/.well-known/did.json': {
      id: '/.well-known/did.json'
      path: '/.well-known/did.json'
      fullPath: '/.well-known/did.json'
      preLoaderRoute: typeof DotwellKnownDidDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/machines/': {
      id: '/_header-layout/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof HeaderLayoutMachinesIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/blog/': {
      id: '/_header-layout/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof HeaderLayoutBlogIndexRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_docs-header-layout/docs/': {
      id: '/_docs-header-layout/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsHeaderLayoutDocsIndexRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/v1/chat/completions': {
      id: '/v1/chat/completions'
      path: '/v1/chat/completions'
      fullPath: '/v1/chat/completions'
      preLoaderRoute: typeof V1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.proxy.putRecord': {
      id: '/api/xrpc/dev.cocore.proxy.putRecord'
      path: '/api/xrpc/dev.cocore.proxy.putRecord'
      fullPath: '/api/xrpc/dev.cocore.proxy.putRecord'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotproxyDotputRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.proxy.deleteRecord': {
      id: '/api/xrpc/dev.cocore.proxy.deleteRecord'
      path: '/api/xrpc/dev.cocore.proxy.deleteRecord'
      fullPath: '/api/xrpc/dev.cocore.proxy.deleteRecord'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.proxy.createRecord': {
      id: '/api/xrpc/dev.cocore.proxy.createRecord'
      path: '/api/xrpc/dev.cocore.proxy.createRecord'
      fullPath: '/api/xrpc/dev.cocore.proxy.createRecord'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotproxyDotcreateRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.inference.dispatch': {
      id: '/api/xrpc/dev.cocore.inference.dispatch'
      path: '/api/xrpc/dev.cocore.inference.dispatch'
      fullPath: '/api/xrpc/dev.cocore.inference.dispatch'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotinferenceDotdispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.devicePair.start': {
      id: '/api/xrpc/dev.cocore.devicePair.start'
      path: '/api/xrpc/dev.cocore.devicePair.start'
      fullPath: '/api/xrpc/dev.cocore.devicePair.start'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotdevicePairDotstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.devicePair.poll': {
      id: '/api/xrpc/dev.cocore.devicePair.poll'
      path: '/api/xrpc/dev.cocore.devicePair.poll'
      fullPath: '/api/xrpc/dev.cocore.devicePair.poll'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotdevicePairDotpollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.devicePair.confirm': {
      id: '/api/xrpc/dev.cocore.devicePair.confirm'
      path: '/api/xrpc/dev.cocore.devicePair.confirm'
      fullPath: '/api/xrpc/dev.cocore.devicePair.confirm'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotdevicePairDotconfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.account.revokeApiKey': {
      id: '/api/xrpc/dev.cocore.account.revokeApiKey'
      path: '/api/xrpc/dev.cocore.account.revokeApiKey'
      fullPath: '/api/xrpc/dev.cocore.account.revokeApiKey'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.account.listApiKeys': {
      id: '/api/xrpc/dev.cocore.account.listApiKeys'
      path: '/api/xrpc/dev.cocore.account.listApiKeys'
      fullPath: '/api/xrpc/dev.cocore.account.listApiKeys'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.account.deleteApiKey': {
      id: '/api/xrpc/dev.cocore.account.deleteApiKey'
      path: '/api/xrpc/dev.cocore.account.deleteApiKey'
      fullPath: '/api/xrpc/dev.cocore.account.deleteApiKey'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xrpc/dev.cocore.account.createApiKey': {
      id: '/api/xrpc/dev.cocore.account.createApiKey'
      path: '/api/xrpc/dev.cocore.account.createApiKey'
      fullPath: '/api/xrpc/dev.cocore.account.createApiKey'
      preLoaderRoute: typeof ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/models': {
      id: '/api/v1/models'
      path: '/api/v1/models'
      fullPath: '/api/v1/models'
      preLoaderRoute: typeof ApiV1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pds/putRecord': {
      id: '/api/pds/putRecord'
      path: '/api/pds/putRecord'
      fullPath: '/api/pds/putRecord'
      preLoaderRoute: typeof ApiPdsPutRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pds/deleteRecord': {
      id: '/api/pds/deleteRecord'
      path: '/api/pds/deleteRecord'
      fullPath: '/api/pds/deleteRecord'
      preLoaderRoute: typeof ApiPdsDeleteRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pds/createRecord': {
      id: '/api/pds/createRecord'
      path: '/api/pds/createRecord'
      fullPath: '/api/pds/createRecord'
      preLoaderRoute: typeof ApiPdsCreateRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/wipe-everything': {
      id: '/api/internal/wipe-everything'
      path: '/api/internal/wipe-everything'
      fullPath: '/api/internal/wipe-everything'
      preLoaderRoute: typeof ApiInternalWipeEverythingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/wipe': {
      id: '/api/internal/wipe'
      path: '/api/internal/wipe'
      fullPath: '/api/internal/wipe'
      preLoaderRoute: typeof ApiInternalWipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/migrate-sessions-to-appview': {
      id: '/api/internal/migrate-sessions-to-appview'
      path: '/api/internal/migrate-sessions-to-appview'
      fullPath: '/api/internal/migrate-sessions-to-appview'
      preLoaderRoute: typeof ApiInternalMigrateSessionsToAppviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/whoami': {
      id: '/api/agent/whoami'
      path: '/api/agent/whoami'
      fullPath: '/api/agent/whoami'
      preLoaderRoute: typeof ApiAgentWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/status': {
      id: '/api/agent/status'
      path: '/api/agent/status'
      fullPath: '/api/agent/status'
      preLoaderRoute: typeof ApiAgentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/health': {
      id: '/api/agent/health'
      path: '/api/agent/health'
      fullPath: '/api/agent/health'
      preLoaderRoute: typeof ApiAgentHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/bug-report': {
      id: '/api/agent/bug-report'
      path: '/api/agent/bug-report'
      fullPath: '/api/agent/bug-report'
      preLoaderRoute: typeof ApiAgentBugReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header-layout/u/$identifier': {
      id: '/_header-layout/u/$identifier'
      path: '/u/$identifier'
      fullPath: '/u/$identifier'
      preLoaderRoute: typeof HeaderLayoutUIdentifierRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/machines/$rkey': {
      id: '/_header-layout/machines/$rkey'
      path: '/machines/$rkey'
      fullPath: '/machines/$rkey'
      preLoaderRoute: typeof HeaderLayoutMachinesRkeyRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/devices/new': {
      id: '/_header-layout/devices/new'
      path: '/devices/new'
      fullPath: '/devices/new'
      preLoaderRoute: typeof HeaderLayoutDevicesNewRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/blog/$slug': {
      id: '/_header-layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof HeaderLayoutBlogSlugRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_header-layout/admin/disputes': {
      id: '/_header-layout/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof HeaderLayoutAdminDisputesRouteImport
      parentRoute: typeof HeaderLayoutRoute
    }
    '/_docs-header-layout/docs/security': {
      id: '/_docs-header-layout/docs/security'
      path: '/docs/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsHeaderLayoutDocsSecurityRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/lexicons': {
      id: '/_docs-header-layout/docs/lexicons'
      path: '/docs/lexicons'
      fullPath: '/docs/lexicons'
      preLoaderRoute: typeof DocsHeaderLayoutDocsLexiconsRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/inference': {
      id: '/_docs-header-layout/docs/inference'
      path: '/docs/inference'
      fullPath: '/docs/inference'
      preLoaderRoute: typeof DocsHeaderLayoutDocsInferenceRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/community-tools': {
      id: '/_docs-header-layout/docs/community-tools'
      path: '/docs/community-tools'
      fullPath: '/docs/community-tools'
      preLoaderRoute: typeof DocsHeaderLayoutDocsCommunityToolsRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/api': {
      id: '/_docs-header-layout/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsHeaderLayoutDocsApiRouteImport
      parentRoute: typeof DocsHeaderLayoutRoute
    }
    '/_docs-header-layout/docs/inference/': {
      id: '/_docs-header-layout/docs/inference/'
      path: '/'
      fullPath: '/docs/inference/'
      preLoaderRoute: typeof DocsHeaderLayoutDocsInferenceIndexRouteImport
      parentRoute: typeof DocsHeaderLayoutDocsInferenceRoute
    }
    '/v1/private/chat/completions': {
      id: '/v1/private/chat/completions'
      path: '/v1/private/chat/completions'
      fullPath: '/v1/private/chat/completions'
      preLoaderRoute: typeof V1PrivateChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/chat/completions': {
      id: '/api/v1/chat/completions'
      path: '/api/v1/chat/completions'
      fullPath: '/api/v1/chat/completions'
      preLoaderRoute: typeof ApiV1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/disputes/resolve': {
      id: '/api/internal/disputes/resolve'
      path: '/api/internal/disputes/resolve'
      fullPath: '/api/internal/disputes/resolve'
      preLoaderRoute: typeof ApiInternalDisputesResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/signup': {
      id: '/api/auth/atproto/signup'
      path: '/api/auth/atproto/signup'
      fullPath: '/api/auth/atproto/signup'
      preLoaderRoute: typeof ApiAuthAtprotoSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/metadata.json': {
      id: '/api/auth/atproto/metadata.json'
      path: '/api/auth/atproto/metadata.json'
      fullPath: '/api/auth/atproto/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/jwks.json': {
      id: '/api/auth/atproto/jwks.json'
      path: '/api/auth/atproto/jwks.json'
      fullPath: '/api/auth/atproto/jwks.json'
      preLoaderRoute: typeof ApiAuthAtprotoJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/callback': {
      id: '/api/auth/atproto/callback'
      path: '/api/auth/atproto/callback'
      fullPath: '/api/auth/atproto/callback'
      preLoaderRoute: typeof ApiAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/authorize': {
      id: '/api/auth/atproto/authorize'
      path: '/api/auth/atproto/authorize'
      fullPath: '/api/auth/atproto/authorize'
      preLoaderRoute: typeof ApiAuthAtprotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/mdm/request-attestation': {
      id: '/api/agent/mdm/request-attestation'
      path: '/api/agent/mdm/request-attestation'
      fullPath: '/api/agent/mdm/request-attestation'
      preLoaderRoute: typeof ApiAgentMdmRequestAttestationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/mdm/push-attestation': {
      id: '/api/agent/mdm/push-attestation'
      path: '/api/agent/mdm/push-attestation'
      fullPath: '/api/agent/mdm/push-attestation'
      preLoaderRoute: typeof ApiAgentMdmPushAttestationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/mdm/nanomdm-webhook': {
      id: '/api/agent/mdm/nanomdm-webhook'
      path: '/api/agent/mdm/nanomdm-webhook'
      fullPath: '/api/agent/mdm/nanomdm-webhook'
      preLoaderRoute: typeof ApiAgentMdmNanomdmWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/mdm/enroll-profile': {
      id: '/api/agent/mdm/enroll-profile'
      path: '/api/agent/mdm/enroll-profile'
      fullPath: '/api/agent/mdm/enroll-profile'
      preLoaderRoute: typeof ApiAgentMdmEnrollProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/mdm/attestation-chain': {
      id: '/api/agent/mdm/attestation-chain'
      path: '/api/agent/mdm/attestation-chain'
      fullPath: '/api/agent/mdm/attestation-chain'
      preLoaderRoute: typeof ApiAgentMdmAttestationChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs-header-layout/docs/inference/authentication': {
      id: '/_docs-header-layout/docs/inference/authentication'
      path: '/authentication'
      fullPath: '/docs/inference/authentication'
      preLoaderRoute: typeof DocsHeaderLayoutDocsInferenceAuthenticationRouteImport
      parentRoute: typeof DocsHeaderLayoutDocsInferenceRoute
    }
    '/_docs-header-layout/docs/inference/$slug': {
      id: '/_docs-header-layout/docs/inference/$slug'
      path: '/$slug'
      fullPath: '/docs/inference/$slug'
      preLoaderRoute: typeof DocsHeaderLayoutDocsInferenceSlugRouteImport
      parentRoute: typeof DocsHeaderLayoutDocsInferenceRoute
    }
    '/api/v1/private/chat/completions': {
      id: '/api/v1/private/chat/completions'
      path: '/api/v1/private/chat/completions'
      fullPath: '/api/v1/private/chat/completions'
      preLoaderRoute: typeof ApiV1PrivateChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsHeaderLayoutDocsInferenceRouteChildren {
  DocsHeaderLayoutDocsInferenceSlugRoute: typeof DocsHeaderLayoutDocsInferenceSlugRoute
  DocsHeaderLayoutDocsInferenceAuthenticationRoute: typeof DocsHeaderLayoutDocsInferenceAuthenticationRoute
  DocsHeaderLayoutDocsInferenceIndexRoute: typeof DocsHeaderLayoutDocsInferenceIndexRoute
}

const DocsHeaderLayoutDocsInferenceRouteChildren: DocsHeaderLayoutDocsInferenceRouteChildren =
  {
    DocsHeaderLayoutDocsInferenceSlugRoute:
      DocsHeaderLayoutDocsInferenceSlugRoute,
    DocsHeaderLayoutDocsInferenceAuthenticationRoute:
      DocsHeaderLayoutDocsInferenceAuthenticationRoute,
    DocsHeaderLayoutDocsInferenceIndexRoute:
      DocsHeaderLayoutDocsInferenceIndexRoute,
  }

const DocsHeaderLayoutDocsInferenceRouteWithChildren =
  DocsHeaderLayoutDocsInferenceRoute._addFileChildren(
    DocsHeaderLayoutDocsInferenceRouteChildren,
  )

interface DocsHeaderLayoutRouteChildren {
  DocsHeaderLayoutDocsApiRoute: typeof DocsHeaderLayoutDocsApiRoute
  DocsHeaderLayoutDocsCommunityToolsRoute: typeof DocsHeaderLayoutDocsCommunityToolsRoute
  DocsHeaderLayoutDocsInferenceRoute: typeof DocsHeaderLayoutDocsInferenceRouteWithChildren
  DocsHeaderLayoutDocsLexiconsRoute: typeof DocsHeaderLayoutDocsLexiconsRoute
  DocsHeaderLayoutDocsSecurityRoute: typeof DocsHeaderLayoutDocsSecurityRoute
  DocsHeaderLayoutDocsIndexRoute: typeof DocsHeaderLayoutDocsIndexRoute
}

const DocsHeaderLayoutRouteChildren: DocsHeaderLayoutRouteChildren = {
  DocsHeaderLayoutDocsApiRoute: DocsHeaderLayoutDocsApiRoute,
  DocsHeaderLayoutDocsCommunityToolsRoute:
    DocsHeaderLayoutDocsCommunityToolsRoute,
  DocsHeaderLayoutDocsInferenceRoute:
    DocsHeaderLayoutDocsInferenceRouteWithChildren,
  DocsHeaderLayoutDocsLexiconsRoute: DocsHeaderLayoutDocsLexiconsRoute,
  DocsHeaderLayoutDocsSecurityRoute: DocsHeaderLayoutDocsSecurityRoute,
  DocsHeaderLayoutDocsIndexRoute: DocsHeaderLayoutDocsIndexRoute,
}

const DocsHeaderLayoutRouteWithChildren =
  DocsHeaderLayoutRoute._addFileChildren(DocsHeaderLayoutRouteChildren)

interface HeaderLayoutRouteChildren {
  HeaderLayoutAcceptTermsRoute: typeof HeaderLayoutAcceptTermsRoute
  HeaderLayoutAccountRoute: typeof HeaderLayoutAccountRoute
  HeaderLayoutChatRoute: typeof HeaderLayoutChatRoute
  HeaderLayoutChatPreviewRoute: typeof HeaderLayoutChatPreviewRoute
  HeaderLayoutExploreRoute: typeof HeaderLayoutExploreRoute
  HeaderLayoutFriendsRoute: typeof HeaderLayoutFriendsRoute
  HeaderLayoutJobsRoute: typeof HeaderLayoutJobsRoute
  HeaderLayoutLeaderboardRoute: typeof HeaderLayoutLeaderboardRoute
  HeaderLayoutModelsRoute: typeof HeaderLayoutModelsRoute
  HeaderLayoutPrivacyRoute: typeof HeaderLayoutPrivacyRoute
  HeaderLayoutStartRoute: typeof HeaderLayoutStartRoute
  HeaderLayoutTermsRoute: typeof HeaderLayoutTermsRoute
  HeaderLayoutIndexRoute: typeof HeaderLayoutIndexRoute
  HeaderLayoutAdminDisputesRoute: typeof HeaderLayoutAdminDisputesRoute
  HeaderLayoutBlogSlugRoute: typeof HeaderLayoutBlogSlugRoute
  HeaderLayoutDevicesNewRoute: typeof HeaderLayoutDevicesNewRoute
  HeaderLayoutMachinesRkeyRoute: typeof HeaderLayoutMachinesRkeyRoute
  HeaderLayoutUIdentifierRoute: typeof HeaderLayoutUIdentifierRoute
  HeaderLayoutBlogIndexRoute: typeof HeaderLayoutBlogIndexRoute
  HeaderLayoutMachinesIndexRoute: typeof HeaderLayoutMachinesIndexRoute
}

const HeaderLayoutRouteChildren: HeaderLayoutRouteChildren = {
  HeaderLayoutAcceptTermsRoute: HeaderLayoutAcceptTermsRoute,
  HeaderLayoutAccountRoute: HeaderLayoutAccountRoute,
  HeaderLayoutChatRoute: HeaderLayoutChatRoute,
  HeaderLayoutChatPreviewRoute: HeaderLayoutChatPreviewRoute,
  HeaderLayoutExploreRoute: HeaderLayoutExploreRoute,
  HeaderLayoutFriendsRoute: HeaderLayoutFriendsRoute,
  HeaderLayoutJobsRoute: HeaderLayoutJobsRoute,
  HeaderLayoutLeaderboardRoute: HeaderLayoutLeaderboardRoute,
  HeaderLayoutModelsRoute: HeaderLayoutModelsRoute,
  HeaderLayoutPrivacyRoute: HeaderLayoutPrivacyRoute,
  HeaderLayoutStartRoute: HeaderLayoutStartRoute,
  HeaderLayoutTermsRoute: HeaderLayoutTermsRoute,
  HeaderLayoutIndexRoute: HeaderLayoutIndexRoute,
  HeaderLayoutAdminDisputesRoute: HeaderLayoutAdminDisputesRoute,
  HeaderLayoutBlogSlugRoute: HeaderLayoutBlogSlugRoute,
  HeaderLayoutDevicesNewRoute: HeaderLayoutDevicesNewRoute,
  HeaderLayoutMachinesRkeyRoute: HeaderLayoutMachinesRkeyRoute,
  HeaderLayoutUIdentifierRoute: HeaderLayoutUIdentifierRoute,
  HeaderLayoutBlogIndexRoute: HeaderLayoutBlogIndexRoute,
  HeaderLayoutMachinesIndexRoute: HeaderLayoutMachinesIndexRoute,
}

const HeaderLayoutRouteWithChildren = HeaderLayoutRoute._addFileChildren(
  HeaderLayoutRouteChildren,
)

interface AgentRouteChildren {
  AgentAppRoute: typeof AgentAppRoute
  AgentBinaryHashesRoute: typeof AgentBinaryHashesRoute
  AgentDlRoute: typeof AgentDlRoute
  AgentInferenceRoute: typeof AgentInferenceRoute
  AgentPolicyRoute: typeof AgentPolicyRoute
  AgentUninstallRoute: typeof AgentUninstallRoute
  AgentVersionRoute: typeof AgentVersionRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAppRoute: AgentAppRoute,
  AgentBinaryHashesRoute: AgentBinaryHashesRoute,
  AgentDlRoute: AgentDlRoute,
  AgentInferenceRoute: AgentInferenceRoute,
  AgentPolicyRoute: AgentPolicyRoute,
  AgentUninstallRoute: AgentUninstallRoute,
  AgentVersionRoute: AgentVersionRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DocsHeaderLayoutRoute: DocsHeaderLayoutRouteWithChildren,
  HeaderLayoutRoute: HeaderLayoutRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  LoginRoute: LoginRoute,
  OgDotpngRoute: OgDotpngRoute,
  DotwellKnownDidDotjsonRoute: DotwellKnownDidDotjsonRoute,
  ExchangeDidDotjsonRoute: ExchangeDidDotjsonRoute,
  LexiconsNsidRoute: LexiconsNsidRoute,
  V1ModelsRoute: V1ModelsRoute,
  V1RecommendedModelsRoute: V1RecommendedModelsRoute,
  XrpcDevDotcocoreDotaccountDotcreateApiKeyRoute:
    XrpcDevDotcocoreDotaccountDotcreateApiKeyRoute,
  XrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute:
    XrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute,
  XrpcDevDotcocoreDotaccountDotlistApiKeysRoute:
    XrpcDevDotcocoreDotaccountDotlistApiKeysRoute,
  XrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute:
    XrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute,
  LexiconsIndexRoute: LexiconsIndexRoute,
  ApiAgentBugReportRoute: ApiAgentBugReportRoute,
  ApiAgentHealthRoute: ApiAgentHealthRoute,
  ApiAgentStatusRoute: ApiAgentStatusRoute,
  ApiAgentWhoamiRoute: ApiAgentWhoamiRoute,
  ApiInternalMigrateSessionsToAppviewRoute:
    ApiInternalMigrateSessionsToAppviewRoute,
  ApiInternalWipeRoute: ApiInternalWipeRoute,
  ApiInternalWipeEverythingRoute: ApiInternalWipeEverythingRoute,
  ApiPdsCreateRecordRoute: ApiPdsCreateRecordRoute,
  ApiPdsDeleteRecordRoute: ApiPdsDeleteRecordRoute,
  ApiPdsPutRecordRoute: ApiPdsPutRecordRoute,
  ApiV1ModelsRoute: ApiV1ModelsRoute,
  ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRoute:
    ApiXrpcDevDotcocoreDotaccountDotcreateApiKeyRoute,
  ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute:
    ApiXrpcDevDotcocoreDotaccountDotdeleteApiKeyRoute,
  ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRoute:
    ApiXrpcDevDotcocoreDotaccountDotlistApiKeysRoute,
  ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute:
    ApiXrpcDevDotcocoreDotaccountDotrevokeApiKeyRoute,
  ApiXrpcDevDotcocoreDotdevicePairDotconfirmRoute:
    ApiXrpcDevDotcocoreDotdevicePairDotconfirmRoute,
  ApiXrpcDevDotcocoreDotdevicePairDotpollRoute:
    ApiXrpcDevDotcocoreDotdevicePairDotpollRoute,
  ApiXrpcDevDotcocoreDotdevicePairDotstartRoute:
    ApiXrpcDevDotcocoreDotdevicePairDotstartRoute,
  ApiXrpcDevDotcocoreDotinferenceDotdispatchRoute:
    ApiXrpcDevDotcocoreDotinferenceDotdispatchRoute,
  ApiXrpcDevDotcocoreDotproxyDotcreateRecordRoute:
    ApiXrpcDevDotcocoreDotproxyDotcreateRecordRoute,
  ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRoute:
    ApiXrpcDevDotcocoreDotproxyDotdeleteRecordRoute,
  ApiXrpcDevDotcocoreDotproxyDotputRecordRoute:
    ApiXrpcDevDotcocoreDotproxyDotputRecordRoute,
  V1ChatCompletionsRoute: V1ChatCompletionsRoute,
  ApiAgentMdmAttestationChainRoute: ApiAgentMdmAttestationChainRoute,
  ApiAgentMdmEnrollProfileRoute: ApiAgentMdmEnrollProfileRoute,
  ApiAgentMdmNanomdmWebhookRoute: ApiAgentMdmNanomdmWebhookRoute,
  ApiAgentMdmPushAttestationRoute: ApiAgentMdmPushAttestationRoute,
  ApiAgentMdmRequestAttestationRoute: ApiAgentMdmRequestAttestationRoute,
  ApiAuthAtprotoAuthorizeRoute: ApiAuthAtprotoAuthorizeRoute,
  ApiAuthAtprotoCallbackRoute: ApiAuthAtprotoCallbackRoute,
  ApiAuthAtprotoJwksDotjsonRoute: ApiAuthAtprotoJwksDotjsonRoute,
  ApiAuthAtprotoMetadataDotjsonRoute: ApiAuthAtprotoMetadataDotjsonRoute,
  ApiAuthAtprotoSignupRoute: ApiAuthAtprotoSignupRoute,
  ApiInternalDisputesResolveRoute: ApiInternalDisputesResolveRoute,
  ApiV1ChatCompletionsRoute: ApiV1ChatCompletionsRoute,
  V1PrivateChatCompletionsRoute: V1PrivateChatCompletionsRoute,
  ApiV1PrivateChatCompletionsRoute: ApiV1PrivateChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
