import * as stylex from "@stylexjs/stylex";

import { animationDuration } from "../../design-system/theme/animations.stylex";
import { primaryColor, uiColor } from "../../design-system/theme/color.stylex";
import { radius } from "../../design-system/theme/radius.stylex";
import {
  gap,
  horizontalSpace,
  verticalSpace,
} from "../../design-system/theme/semantic-spacing.stylex";
import { shadow } from "../../design-system/theme/shadow.stylex";
import { spacing } from "../../design-system/theme/spacing.stylex";
import {
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  tracking,
} from "../../design-system/theme/typography.stylex";

export const docsCodeColors = stylex.defineConsts({
  bg: "oklch(0.255 0.016 58)",
  bg2: "oklch(0.225 0.015 58)",
  head: "oklch(0.305 0.016 58)",
  fg: "oklch(0.90 0.010 80)",
  faint: "oklch(0.64 0.012 70)",
  line: "oklch(0.36 0.014 60)",
  ok: "oklch(0.62 0.13 150)",
  url: "oklch(0.82 0.07 55)",
  jsonKey: "oklch(0.80 0.085 55)",
  jsonStr: "oklch(0.84 0.040 145)",
  jsonNum: "oklch(0.78 0.075 235)",
});

const REF_BREAK = "@media (max-width: 1280px)";
const NAV_HIDE = "@media (max-width: 960px)";
const DOCS_NAV_WIDTH = "264px";
const DOCS_INTRO_MAX = "56rem";
const DOCS_TOPBAR_HEIGHT = spacing["16"];

export const docsStyles = stylex.create({
  page: {
    backgroundColor: uiColor.bg,
    color: uiColor.text2,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.base,
    lineHeight: 1.6,
    maxWidth: "100%",
    minHeight: "100vh",
    overflowX: "clip",
  },
  topbar: {
    alignItems: "center",
    backdropFilter: "blur(10px)",
    backgroundColor: "light-dark(oklch(0.985 0.007 85 / 0.9), oklch(0.16 0.012 60 / 0.9))",
    boxSizing: "border-box",
    display: "flex",
    flexWrap: "wrap",
    gap: spacing["2"],
    justifyContent: "space-between",
    maxWidth: "100%",
    minWidth: 0,
    position: "sticky",
    zIndex: 20,
    borderBottomColor: uiColor.border1,
    borderBottomStyle: "solid",
    borderBottomWidth: spacing["px"],
    height: DOCS_TOPBAR_HEIGHT,
    paddingBottom: spacing["4"],
    paddingLeft: spacing["4"],
    paddingRight: {
      [NAV_HIDE]: spacing["4"],
      default: spacing["6"],
    },
    paddingTop: spacing["4"],
    top: 0,
  },
  topbarLeft: {
    gap: spacing["4"],
    alignItems: "center",
    display: "flex",
    flexShrink: 1,
    minWidth: 0,
  },
  topbarTag: {
    // eslint-disable-next-line @stylexjs/valid-styles
    textBoxEdge: "cap alphabetic",
    // eslint-disable-next-line @stylexjs/valid-styles
    textBoxTrim: "trim-both",
    color: uiColor.text1,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
    borderLeftColor: uiColor.border1,
    borderLeftStyle: "solid",
    borderLeftWidth: spacing["px"],
    paddingBottom: spacing["2"],
    paddingLeft: spacing["4"],
    paddingTop: spacing["2"],
  },
  topbarTagFull: {
    display: {
      [NAV_HIDE]: "none",
      default: "inline",
    },
  },
  topbarTagShort: {
    display: {
      [NAV_HIDE]: "inline",
      default: "none",
    },
  },
  topbarNav: {
    gap: spacing["1"],
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
  },
  topbarNavLink: {
    borderRadius: radius.sm,
    textDecoration: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": uiColor.bgSubtle,
    },
    color: {
      default: uiColor.text1,
      ":hover": uiColor.text2,
    },
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    paddingBottom: spacing["1.5"],
    paddingLeft: spacing["3.5"],
    paddingRight: spacing["3.5"],
    paddingTop: spacing["1.5"],
  },
  topbarNavLinkActive: {
    backgroundColor: primaryColor.bgSubtle,
    color: primaryColor.text2,
  },
  topbarNavSoon: {
    color: uiColor.text1,
    cursor: "default",
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontStyle: "italic",
    opacity: 0.7,
    paddingBottom: spacing["1.5"],
    paddingLeft: spacing["3.5"],
    paddingRight: spacing["3.5"],
    paddingTop: spacing["1.5"],
  },
  mobileJumpBar: {
    gap: spacing["2"],
    alignItems: "center",
    backdropFilter: "blur(10px)",
    backgroundColor: "light-dark(oklch(0.985 0.007 85 / 0.96), oklch(0.16 0.012 60 / 0.96))",
    boxSizing: "border-box",
    display: {
      [NAV_HIDE]: "flex",
      default: "none",
    },
    maxWidth: "100%",
    minWidth: 0,
    position: "sticky",
    zIndex: 15,
    borderBottomColor: uiColor.border1,
    borderBottomStyle: "solid",
    borderBottomWidth: spacing["px"],
    paddingBottom: spacing["2"],
    paddingLeft: horizontalSpace["3xl"],
    paddingRight: horizontalSpace["3xl"],
    paddingTop: spacing["2"],
    top: DOCS_TOPBAR_HEIGHT,
  },
  mobileJumpLabel: {
    color: uiColor.text1,
    flexShrink: 0,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  mobileJumpSelect: {
    backgroundPosition: "calc(100% - 18px) calc(50% + 1px), calc(100% - 13px) calc(50% + 1px)",
    borderColor: uiColor.border1,
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: spacing["px"],
    appearance: "none",
    backgroundColor: uiColor.component1,
    backgroundImage:
      "linear-gradient(45deg, transparent 50%, currentColor 50%), linear-gradient(135deg, currentColor 50%, transparent 50%)",
    backgroundRepeat: "no-repeat",
    backgroundSize: "5px 5px, 5px 5px",
    boxSizing: "border-box",
    color: uiColor.text2,
    flexBasis: "auto",
    flexGrow: "1",
    flexShrink: "1",
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    minWidth: 0,
    paddingBottom: spacing["2"],
    paddingLeft: spacing["3"],
    paddingRight: spacing["8"],
    paddingTop: spacing["2"],
  },
  refLayout: {
    display: "grid",
    gridTemplateColumns: {
      [NAV_HIDE]: "minmax(0, 1fr)",
      default: `${DOCS_NAV_WIDTH} minmax(0, 1fr)`,
    },
    maxWidth: "100%",
    minWidth: 0,
    width: "100%",
  },
  refNavColumn: {
    backgroundColor: uiColor.bgSubtle,
    borderRightColor: uiColor.border1,
    borderRightStyle: "solid",
    borderRightWidth: spacing["px"],
    display: {
      [NAV_HIDE]: "none",
      default: "block",
    },
    minWidth: 0,
    width: DOCS_NAV_WIDTH,
  },
  refNav: {
    boxSizing: "border-box",
    display: "block",
    height: `calc(100vh - ${DOCS_TOPBAR_HEIGHT})`,
    maxHeight: `calc(100vh - ${DOCS_TOPBAR_HEIGHT})`,
    minWidth: 0,
    overflowX: "hidden",
    overflowY: "auto",
    paddingBottom: spacing["10"],
    paddingLeft: horizontalSpace["3xl"],
    paddingRight: horizontalSpace["3xl"],
    paddingTop: spacing["9"],
    position: "sticky",
    top: DOCS_TOPBAR_HEIGHT,
    width: "100%",
  },
  refNavGroup: {
    marginBottom: spacing["6"],
    minWidth: 0,
  },
  refNavHeadingRow: {
    gap: spacing["1"],
    alignItems: "baseline",
    display: "flex",
    justifyContent: "space-between",
    marginBottom: spacing["2.5"],
    minWidth: 0,
  },
  refNavHeading: {
    overflow: "hidden",
    color: uiColor.text1,
    flexBasis: "auto",
    flexGrow: "1",
    flexShrink: "1",
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: "0.14em",
    textOverflow: "ellipsis",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
    minWidth: 0,
  },
  refNavHeadingCount: {
    color: uiColor.text1,
    flexShrink: 0,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.xs,
  },
  refNavLink: {
    borderRadius: radius.sm,
    overflow: "hidden",
    textDecoration: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": uiColor.component1,
    },
    color: {
      default: uiColor.solid2,
      ":hover": uiColor.text2,
    },
    display: "block",
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
    paddingBottom: spacing["1"],
    paddingLeft: spacing["2.5"],
    paddingRight: spacing["2.5"],
    paddingTop: spacing["1"],
  },
  refNavLinkMono: {
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
  },
  refNavLinkActive: {
    backgroundColor: primaryColor.bgSubtle,
    color: primaryColor.text2,
    fontWeight: fontWeight.medium,
  },
  refNavSoon: {
    color: uiColor.text1,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontStyle: "italic",
    paddingBottom: spacing["1"],
    paddingLeft: spacing["2.5"],
    paddingRight: spacing["2.5"],
    paddingTop: spacing["1"],
  },
  refMain: {
    boxSizing: "border-box",
    maxWidth: "100%",
    minWidth: 0,
    overflowX: "clip",
    paddingBottom: spacing["24"],
    paddingLeft: {
      [NAV_HIDE]: horizontalSpace["3xl"],
      default: spacing["12"],
    },
    paddingRight: {
      [NAV_HIDE]: horizontalSpace["3xl"],
      default: spacing["12"],
    },
    paddingTop: {
      [NAV_HIDE]: spacing["6"],
      default: spacing["10"],
    },
    width: "100%",
  },
  masthead: {
    maxWidth: DOCS_INTRO_MAX,
    paddingBottom: spacing["9"],
    paddingTop: spacing["12"],
    scrollMarginTop: {
      [NAV_HIDE]: spacing["32"],
      default: spacing["20"],
    },
  },
  pageHead: {
    maxWidth: DOCS_INTRO_MAX,
    paddingBottom: spacing["6"],
    paddingTop: spacing["10"],
  },
  pageTitle: {
    color: uiColor.text2,
    fontFamily: fontFamily.title,
    fontSize: {
      default: fontSize["4xl"],
      "@media (max-width: 47.5rem)": fontSize["3xl"],
    },
    fontWeight: fontWeight.extrabold,
    letterSpacing: tracking.tight,
    lineHeight: lineHeight.sm,
    marginBottom: verticalSpace.none,
    marginTop: spacing["3"],
  },
  pageDek: {
    color: uiColor.text1,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.lg,
    lineHeight: lineHeight.base,
    marginBottom: verticalSpace.none,
    marginTop: spacing["3"],
    maxWidth: "58ch",
  },
  introProse: {
    maxWidth: DOCS_INTRO_MAX,
    overflowWrap: "anywhere",
  },
  kicker: {
    color: uiColor.text1,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    letterSpacing: "0.2em",
    textTransform: "uppercase",
  },
  title: {
    color: uiColor.text2,
    fontFamily: fontFamily.title,
    fontSize: {
      default: fontSize["6xl"],
      "@media (max-width: 47.5rem)": fontSize["5xl"],
    },
    fontWeight: fontWeight.extrabold,
    letterSpacing: tracking.tight,
    lineHeight: lineHeight.sm,
    marginBottom: verticalSpace.none,
    marginTop: spacing["3.5"],
  },
  dek: {
    color: uiColor.text1,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xl,
    lineHeight: lineHeight.base,
    marginBottom: verticalSpace.none,
    marginTop: spacing["4"],
    maxWidth: "58ch",
  },
  baseUrl: {
    borderColor: uiColor.border1,
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: spacing["px"],
    gap: spacing["2.5"],
    alignItems: "center",
    backgroundColor: uiColor.component1,
    boxShadow: shadow.sm,
    color: uiColor.solid2,
    display: "inline-flex",
    flexWrap: "wrap",
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    marginTop: spacing["5"],
    paddingBottom: spacing["2"],
    paddingLeft: spacing["3.5"],
    paddingRight: spacing["3.5"],
    paddingTop: spacing["2"],
  },
  baseUrlLabel: {
    color: uiColor.text1,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  baseUrlDot: {
    color: uiColor.border2,
  },
  baseUrlOk: {
    gap: spacing["1"],
    alignItems: "center",
    color: docsCodeColors.ok,
    display: "inline-flex",
  },
  baseUrlOkDot: {
    borderRadius: radius.full,
    backgroundColor: docsCodeColors.ok,
    height: spacing["1.5"],
    width: spacing["1.5"],
  },
  h2: {
    color: uiColor.text2,
    fontFamily: fontFamily.sans,
    fontSize: fontSize["2xl"],
    fontWeight: fontWeight.bold,
    letterSpacing: "-0.01em",
    marginBottom: spacing["4"],
    marginTop: spacing["12"],
    scrollMarginTop: {
      [NAV_HIDE]: spacing["32"],
      default: spacing["20"],
    },
  },
  h2First: {
    marginTop: spacing["2"],
  },
  prose: {
    color: uiColor.solid2,
    fontFamily: fontFamily.sans,
    lineHeight: lineHeight.base,
    marginBottom: spacing["4"],
    maxWidth: "72ch",
  },
  proseList: {
    color: uiColor.solid2,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.base,
    lineHeight: lineHeight.base,
    listStylePosition: "outside",
    marginBottom: spacing["4"],
    marginTop: spacing["2"],
    paddingLeft: spacing["10"],
  },
  proseListItem: {
    marginBottom: spacing["2"],
    paddingLeft: spacing["1"],
  },
  proseLink: {
    textDecoration: "underline",
    color: primaryColor.text2,
    textUnderlineOffset: spacing["3"],
  },
  codeInline: {
    borderColor: uiColor.border1,
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: spacing["px"],
    backgroundColor: uiColor.bgSubtle,
    // eslint-disable-next-line @stylexjs/valid-styles
    boxDecorationBreak: "clone",
    color: uiColor.text2,
    fontFamily: fontFamily.mono,
    fontSize: "0.86em",
    overflowWrap: "anywhere",
    paddingBottom: spacing["px"],
    paddingLeft: spacing["1.5"],
    paddingRight: spacing["1.5"],
    paddingTop: spacing["px"],
  },
  codeInlineAccent: {
    borderColor: "transparent",
    backgroundColor: primaryColor.bgSubtle,
    color: primaryColor.text2,
  },
  tierHead: {
    gap: spacing["3.5"],
    alignItems: "baseline",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: spacing["2"],
    borderBottomColor: uiColor.border2,
    borderBottomStyle: "solid",
    borderBottomWidth: spacing["0.5"],
    marginBottom: spacing["1.5"],
    marginTop: spacing["16"],
    minWidth: 0,
    paddingBottom: spacing["3.5"],
    scrollMarginTop: {
      [NAV_HIDE]: spacing["32"],
      default: spacing["5"],
    },
  },
  tierTitle: {
    color: uiColor.text2,
    flexBasis: "auto",
    flexGrow: "1",
    flexShrink: "1",
    fontFamily: fontFamily.sans,
    fontSize: fontSize["3xl"],
    fontWeight: fontWeight.extrabold,
    letterSpacing: "-0.02em",
    marginBottom: verticalSpace.none,
    marginTop: verticalSpace.none,
    minWidth: 0,
  },
  tierSub: {
    color: uiColor.text1,
    flexShrink: 1,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.xs,
    marginLeft: "auto",
    minWidth: 0,
    textAlign: "right",
  },
  endpoint: {
    borderTopColor: uiColor.border1,
    borderTopStyle: "solid",
    borderTopWidth: spacing["px"],
    maxWidth: "100%",
    minWidth: 0,
    overflowX: "clip",
    paddingBottom: spacing["10"],
    paddingTop: spacing["10"],
    scrollMarginTop: {
      [NAV_HIDE]: spacing["32"],
      default: spacing["20"],
    },
  },
  endpointFirst: {
    borderTopWidth: 0,
  },
  inferenceSection: {
    maxWidth: "100%",
    minWidth: 0,
    scrollMarginTop: {
      [NAV_HIDE]: spacing["32"],
      default: spacing["20"],
    },
  },
  endpointGrid: {
    gap: spacing["11"],
    alignItems: "start",
    display: "grid",
    gridTemplateColumns: {
      [REF_BREAK]: "minmax(0, 1fr)",
      default: "minmax(0, 1fr) minmax(0, 1fr)",
    },
    maxWidth: "100%",
    minWidth: 0,
    width: "100%",
  },
  endpointLeft: {
    minWidth: 0,
  },
  endpointRight: {
    position: {
      [REF_BREAK]: "static",
      default: "sticky",
    },
    minWidth: 0,
    top: spacing["7"],
  },
  nsidRow: {
    gap: spacing["3"],
    alignItems: "center",
    color: uiColor.text2,
    display: "flex",
    flexWrap: "wrap",
    fontFamily: fontFamily.mono,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.medium,
    letterSpacing: "-0.01em",
    maxWidth: "100%",
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  nsidDim: {
    color: uiColor.text1,
  },
  methodBadge: {
    borderRadius: radius.sm,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    paddingBottom: spacing["1"],
    paddingLeft: spacing["2"],
    paddingRight: spacing["2"],
    paddingTop: spacing["1"],
  },
  methodBadgeQuery: {
    backgroundColor: "light-dark(oklch(0.94 0.03 215), oklch(0.28 0.04 215))",
    color: "light-dark(oklch(0.50 0.10 215), oklch(0.78 0.08 215))",
  },
  methodBadgeProcedure: {
    backgroundColor: primaryColor.bgSubtle,
    color: primaryColor.text2,
  },
  lexiconBadgeRecord: {
    backgroundColor: "light-dark(oklch(0.94 0.03 145), oklch(0.28 0.04 145))",
    color: "light-dark(oklch(0.48 0.10 145), oklch(0.78 0.08 145))",
  },
  lexiconBadgeDefs: {
    backgroundColor: "light-dark(oklch(0.94 0.02 70), oklch(0.28 0.03 70))",
    color: "light-dark(oklch(0.50 0.08 70), oklch(0.78 0.06 70))",
  },
  lexiconFieldsLabel: {
    color: uiColor.text1,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    marginBottom: verticalSpace.none,
    marginTop: spacing["5"],
  },
  lexiconFieldDesc: {
    color: uiColor.text1,
    display: "block",
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    lineHeight: lineHeight.sm,
    marginTop: spacing["1"],
  },
  authBadge: {
    gap: spacing["1.5"],
    alignItems: "center",
    color: uiColor.text1,
    display: "inline-flex",
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
  },
  authDot: {
    borderRadius: radius.full,
    backgroundColor: uiColor.border2,
    height: spacing["1"],
    width: spacing["1"],
  },
  authDotRequired: {
    backgroundColor: primaryColor.solid1,
  },
  endpointDesc: {
    color: uiColor.solid2,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.base,
    lineHeight: lineHeight.base,
    marginBottom: verticalSpace.none,
    marginTop: spacing["3"],
  },
  paramTable: {
    borderCollapse: "collapse",
    marginTop: spacing["5"],
    maxWidth: "100%",
    tableLayout: "fixed",
    width: "100%",
  },
  paramTh: {
    color: uiColor.text1,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: "0.06em",
    textAlign: "left",
    textTransform: "uppercase",
    borderBottomColor: uiColor.border2,
    borderBottomStyle: "solid",
    borderBottomWidth: spacing["px"],
    paddingBottom: spacing["2"],
  },
  paramTd: {
    verticalAlign: "top",
    borderBottomColor: uiColor.border1,
    borderBottomStyle: "solid",
    borderBottomWidth: spacing["px"],
    paddingBottom: spacing["2.5"],
    paddingTop: spacing["2.5"],
  },
  paramName: {
    color: uiColor.text2,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  paramRequired: {
    color: primaryColor.solid1,
    marginLeft: spacing["2"],
  },
  paramType: {
    color: "light-dark(oklch(0.50 0.10 215), oklch(0.78 0.08 215))",
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  reqPanel: {
    borderColor: "oklch(0.205 0.014 58)",
    borderRadius: radius.sm,
    borderStyle: "solid",
    borderWidth: spacing["px"],
    backgroundColor: docsCodeColors.bg,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    maxHeight: "80vh",
    maxWidth: "100%",
    minWidth: 0,
    overflowX: "hidden",
    overflowY: "auto",
    width: "100%",
  },
  reqBar: {
    gap: spacing["2.5"],
    alignItems: "center",
    backgroundColor: docsCodeColors.head,
    display: "flex",
    borderBottomColor: docsCodeColors.line,
    borderBottomStyle: "solid",
    borderBottomWidth: spacing["px"],
    paddingBottom: spacing["2.5"],
    paddingLeft: spacing["3.5"],
    paddingRight: spacing["3.5"],
    paddingTop: spacing["2.5"],
  },
  reqTag: {
    color: docsCodeColors.faint,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: "0.16em",
    textTransform: "uppercase",
  },
  reqSpacer: {
    flexBasis: "0%",
    flexGrow: "1",
    flexShrink: "1",
  },
  reqBtn: {
    borderRadius: radius.sm,
    borderStyle: "none",
    gap: spacing["1.5"],
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "oklch(1 0 0 / 0.07)",
    },
    color: docsCodeColors.fg,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    paddingBottom: spacing["1"],
    paddingLeft: spacing["2"],
    paddingRight: spacing["2"],
    paddingTop: spacing["1"],
  },
  reqBtnSolid: {
    borderColor: primaryColor.border2,
    borderStyle: "solid",
    borderWidth: spacing["px"],
    backgroundColor: {
      default: primaryColor.solid1,
      ":hover": primaryColor.text2,
    },
    color: uiColor.textContrast,
  },
  reqBtnDisabled: {
    cursor: "not-allowed",
    opacity: 0.65,
  },
  reqCode: {
    boxSizing: "border-box",
    color: docsCodeColors.fg,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    lineHeight: 1.7,
    marginBottom: verticalSpace.none,
    marginTop: verticalSpace.none,
    maxWidth: "100%",
    minWidth: 0,
    overflowWrap: "anywhere",
    overflowX: "auto",
    paddingBottom: spacing["3.5"],
    paddingLeft: spacing["4"],
    paddingRight: spacing["4"],
    paddingTop: spacing["3.5"],
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
  },
  reqCodeFlag: {
    color: docsCodeColors.faint,
  },
  reqCodeUrl: {
    color: docsCodeColors.url,
  },
  reqParams: {
    alignItems: "center",
    borderBottomColor: docsCodeColors.line,
    borderBottomStyle: "solid",
    borderBottomWidth: spacing["px"],
    columnGap: spacing["3"],
    display: "grid",
    gridTemplateColumns: "minmax(6.75rem, max-content) minmax(0, 1fr)",
    paddingBottom: spacing["3"],
    paddingLeft: spacing["4"],
    paddingRight: spacing["4"],
    paddingTop: spacing["3"],
    rowGap: gap.sm,
  },
  reqParamRow: {
    display: "contents",
  },
  reqParamLabel: {
    color: docsCodeColors.faint,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    justifySelf: "end",
    textAlign: "right",
  },
  reqParamControl: {
    minWidth: spacing["0"],
    width: "100%",
  },
  jsonKey: {
    color: docsCodeColors.jsonKey,
  },
  jsonStr: {
    color: docsCodeColors.jsonStr,
  },
  jsonNum: {
    color: docsCodeColors.jsonNum,
  },
  jsonBool: {
    color: docsCodeColors.jsonNum,
  },
  jsonNull: {
    color: docsCodeColors.faint,
  },
  respBar: {
    gap: spacing["2.5"],
    alignItems: "center",
    backgroundColor: docsCodeColors.bg2,
    display: "flex",
    borderBottomColor: docsCodeColors.line,
    borderBottomStyle: "solid",
    borderBottomWidth: spacing["px"],
    borderTopColor: docsCodeColors.line,
    borderTopStyle: "solid",
    borderTopWidth: spacing["px"],
    paddingBottom: spacing["2"],
    paddingLeft: spacing["4"],
    paddingRight: spacing["4"],
    paddingTop: spacing["2"],
  },
  respStatusOk: {
    color: docsCodeColors.ok,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    marginLeft: "auto",
  },
  respStatusErr: {
    color: docsCodeColors.faint,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    marginLeft: "auto",
  },
  respMeta: {
    color: docsCodeColors.faint,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.xs,
    paddingBottom: spacing["0.5"],
    paddingLeft: spacing["4"],
    paddingRight: spacing["4"],
    paddingTop: spacing["2.5"],
  },
  respJsonPending: {
    opacity: 0.45,
  },
  respJson: {
    boxSizing: "border-box",
    color: docsCodeColors.fg,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    lineHeight: 1.65,
    marginBottom: verticalSpace.none,
    marginTop: verticalSpace.none,
    maxWidth: "100%",
    minWidth: 0,
    overflowWrap: "anywhere",
    overflowX: "auto",
    paddingBottom: spacing["4"],
    paddingLeft: spacing["4"],
    paddingRight: spacing["4"],
    paddingTop: spacing["1.5"],
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  respEmpty: {
    color: docsCodeColors.faint,
    fontFamily: fontFamily.sans,
    fontSize: fontSize.sm,
    fontStyle: "italic",
    paddingBottom: spacing["4"],
    paddingLeft: spacing["4"],
    paddingRight: spacing["4"],
    paddingTop: spacing["4"],
  },
  spin: {
    animationDuration: animationDuration.slow,
    animationIterationCount: "infinite",
    animationName: stylex.keyframes({
      to: { transform: "rotate(360deg)" },
    }),
    animationTimingFunction: "linear",
    borderBottomColor: "oklch(1 0 0 / 0.3)",
    borderLeftColor: "oklch(1 0 0 / 0.3)",
    borderRadius: radius.full,
    borderRightColor: "oklch(1 0 0 / 0.3)",
    borderStyle: "solid",
    borderTopColor: "oklch(0.99 0.01 80)",
    borderWidth: spacing["0.5"],
    boxSizing: "border-box",
    flexShrink: 0,
    height: spacing["3"],
    width: spacing["3"],
  },
});
